import { Allow } from 'class-validator';
export class CreateFoodFeedsInput {
    @Allow() id: number;
    @Allow() user_id: number;
    @Allow() userName: string;
    @Allow() appId: string;
    @Allow() logType: string;
    @Allow() appName: string;
    @Allow() logId: number;
    @Allow() foodId: string;
    @Allow() locale: string;
    @Allow() mealTypeId: number;
    @Allow() name: string;
    @Allow() calories: number;
    @Allow() carbs: number;
    @Allow() fat: number;
    @Allow() fiber: number;
    @Allow() protein: number;
    @Allow() sodium: number;
    @Allow() water: number;
    @Allow() logDate: string;
    @Allow() isFavorite: string;
    @Allow() accessLevel: string;
    @Allow() amount: number;
    @Allow() foodUnit: string;
    @Allow() collectionDate: string;
    @Allow() activityTypeId: number;
    @Allow() activityType: string;
    @Allow() action: string;
    @Allow() type: string;
    @Allow() status: number;
    @Allow() challenge_id: string;
}
