import { Expose } from 'class-transformer';
export class ThemesDto {
    @Expose() id: number;
    @Expose() themename: string;
    @Expose() themetype: string;
    @Expose() bodycolor: string;
    @Expose() bodyfontcolor: string;
    @Expose() pagecontentbgcolor: string;
    @Expose() headercolor: string;
    @Expose() mainnavigationactive: string;
    @Expose() subnavigationactive: string;
    @Expose() navigationfontcolor: string;
    @Expose() pagetitlebgcolor: string;
    @Expose() mainpagetitlecolor: string;
    @Expose() pagetitlecolor: string;
    @Expose() innercontentcolor: string;
    @Expose() breadbgcolor: string;
    @Expose() breadfontcolor: string;
    @Expose() linkcolor: string;
    @Expose() sidetogcolor: string;
    @Expose() successbgcolor: string;
    @Expose() successfontcolor: string;
    @Expose() errorbgcolor: string;
    @Expose() errorfontcolor: string;
    @Expose() btndarkbgcolor: string;
    @Expose() btndarkhovercolor: string;
    @Expose() btngreenbgcolor: string;
    @Expose() btngreenhovercolor: string;
    @Expose() bodywithallcolor: string;
    @Expose() navigationallcolor: string;
    @Expose() esubnavigationactive: string;
    @Expose() pagewithallcolor: string;
    @Expose() status: number;
    @Expose() added_date: string;
    @Expose() updated_date: string;
}
