import { Allow } from 'class-validator';
export class CreateChallengeInput {
    @Allow() uid: number;
    @Allow() challenge_name: string;
    @Allow() challenge_desc: string;
    @Allow() challenge_type: string;
    @Allow() icon: string;
    @Allow() logo: string;
    @Allow() biomatrics: string;
    @Allow() biomatrics_criteria: string;
    @Allow() data_entry: string;
    @Allow() data_interval: string;
    @Allow() bio_challenge_type: string;
    @Allow() activity_id: number;
    @Allow() activity_desc: string;
    @Allow() stepactivity_type: string;
    @Allow() max_time_day: number;
    @Allow() numberofsteps: number;
    @Allow() startdate: string;
    @Allow() enddate: string;
    @Allow() weektimeframe: number;
    @Allow() requirementbased: number;
    @Allow() numberofday: number;
    @Allow() numberofweek: number;
    @Allow() oz_water_per_day: number;
    @Allow() status: number;
    @Allow() company_id: string;
    @Allow() weeks: any;
    @Allow() fitness: any;
}
