import { Allow } from 'class-validator';
export class CreateSlotsInput {
    @Allow() ev_events_id: number;
    @Allow() organization_id: number;
    @Allow() slot_timezone: number;
    @Allow() start_date: string;
    @Allow() end_date: string;
    @Allow() start_time: string;
    @Allow() end_time: string;
    @Allow() slot_hour: number;
    @Allow() dividing_slot_type: number;
    @Allow() slot_interval: string;
    @Allow() slot_total: number;
    @Allow() attendee_limit_type: number;
    @Allow() attendee_limit: number;
    @Allow() recurring_pattern_type: number;
    @Allow() weekly_basis_day: string;
    @Allow() weekly_basis_day_bio: string;
    @Allow() monthly_basis: number;
    @Allow() monthly_date_basis: string;
    @Allow() monthly_basis_Type: number;
    @Allow() monthly_basis_day: number;
    @Allow() year_basis_day: number;
    @Allow() year_basis_month: number;
    @Allow() slot_visibility_locations: string;
    @Allow() slot_visibility_departments: string;
    @Allow() event_location: string;
    @Allow() event_address: string;
    @Allow() event_city: string;
    @Allow() event_state: string;
    @Allow() event_zipcode: string;
    @Allow() booking_price: number;
    @Allow() status: number;
    @Allow() created_by: number;
    @Allow() registration_end: number;
}
