import { Allow } from 'class-validator';
export class CreateCommunicationEmailCampaignRequestsInput {
    @Allow() id: number;
    @Allow() subject: string;
    @Allow() file: string;
    @Allow() from_email_id: number;
    @Allow() template_content: string;
    @Allow() schedule_datetime: string;
    @Allow() interval_from: string;
    @Allow() interval_to: string;
    @Allow() success_count: number;
    @Allow() fail_count: number;
    @Allow() sheet_header: string;
    @Allow() hash: string;
    @Allow() timezone: string;
    @Allow() test_mail_user_data: string;
    @Allow() campaign_title: string;
    @Allow() request_status: number;
    @Allow() attachment: string;
    @Allow() request_flag: number;
    @Allow() duplicate_record: number;
    @Allow() total_reschedule: number;
    @Allow() role_id: number;
    @Allow() approval_status: number;
    @Allow() approval_status_data: string;
    @Allow() testemail: string;
    @Allow() sendtestmailstatus: number;
    @Allow() for_org_id: number;
    @Allow() with_option: string;
    @Allow() org_filter_data: string;
    @Allow() use_def_tem_id: number;
    @Allow() group_id: number;
    @Allow() parent_id: number;
    @Allow() template_type: number;
    @Allow() template_item_id: string | 0;
    @Allow() copied: number;
    @Allow() details_type: number;
    @Allow() test_user_role: string;
    @Allow() template_item_sub_id: string;
    @Allow() test_user_id: number;
    @Allow() created_by: number;
    @Allow() updated_by: number;
    @Allow() status: number;
    @Allow() schedule_utc_datetime: string;
}
