import { Allow } from 'class-validator';
export class UpdateWeeksInput {
    @Allow() id: number;
    @Allow() challenge_id: number;
    @Allow() activity_id: number;
    @Allow() site_activity_desc: string;
    @Allow() manual_activity: string;
    @Allow() manual_desc: string;
    @Allow() completion_status: number;
    @Allow() log_status: number;
    @Allow() meal: string;
    @Allow() amount: number;
    @Allow() quantity: number;
    @Allow() steps: string;
    @Allow() duration: string;
    @Allow() distance: string;
    @Allow() calories: string;
    @Allow() tabacco_status: string;
    @Allow() avalue: number;
    @Allow() waterlogunit: string;
    @Allow() m_numeric: string;
    @Allow() m_short: string;
    @Allow() m_long: string;
    @Allow() m_yesno: string;
    @Allow() m_check: string;
    @Allow() m_field: string;
    @Allow() logofile: string;
    @Allow() status: number;
    @Allow() tabmanual: string;
}
