import { Allow } from 'class-validator';
export class CreateAssessmentHraBiometricInput {
    @Allow() id: number;
    @Allow() user_id: number;
    @Allow() activity_id: string;
    @Allow() weight: string;
    @Allow() height_ft: string;
    @Allow() height_in: string;
    @Allow() weight_source: number;
    @Allow() bp_systolic: string;
    @Allow() bp_diastolic: string;
    @Allow() bp_source: number;
    @Allow() blood_glucose: string;
    @Allow() test_type: number;
    @Allow() blood_glucose_source: number;
    @Allow() alc: string;
    @Allow() date: string;
    @Allow() total_cholesterol: string;
    @Allow() hdl: string;
    @Allow() ldl: string;
    @Allow() atriskldl: number;
    @Allow() triglycerides: string;
    @Allow() cholestrol_source: number;
    @Allow() body_fat: number;
    @Allow() body_fat_source: number;
    @Allow() hip: number;
    @Allow() waist: number;
    @Allow() arm: number;
    @Allow() leg: number;
    @Allow() calve: number;
    @Allow() measurement_source: number;
    @Allow() source: number;
    @Allow() status: number;
}
