import { Allow } from 'class-validator';
import { PaginateInput } from './paginate.input';
export class PaginateWithCompanyInput extends PaginateInput {
    @Allow() company_id?: string;
    @Allow() role_id?: number;
    @Allow() campaign_id?: number;
    @Allow() event_id?: number;
    @Allow() organization_id?: string;
    @Allow() c_companies_id?: string;
    @Allow() quicklink_id?: number;
    @Allow() activity_id?: number;
    @Allow() created_by_user_id?: number;
    @Allow() ev_events_id?: number;
    @Allow() ev_slots_id?: number;
    @Allow() quiz_id?: string;
    @Allow() status?: number;
    @Allow() request_date?: string;
    @Allow() is_testing?: string;
    @Allow() filter_by?: string;
    @Allow() cat_id?: number;
    @Allow() submitted_date?: string;
    @Allow() upload_date?: string;
    @Allow() section_id?: string;
    @Allow() plan_id?: number;
    @Allow() plan_ids?: string;
    @Allow() block_id?: number;
    @Allow() flag_status?: string;
    @Allow() request_type?: string;
    @Allow() global_folder?: number;
    @Allow() plan_order?: number;
    @Allow() is_sanmateo?: number;
    @Allow() year?: number;
    @Allow() type?: string;
    @Allow() department_id?: string;
    @Allow() location_id?: string;
    @Allow() state?: string;
    @Allow() city?: string;
    @Allow() fields?: string[];
}
