import 'dotenv/config';
export const appConstant = {
    PUBLIC_PATH: './public/',
    COMPANY_LOGO_PATH: './public/upload/company/',
    COMPANY_CHAMPION_LOGO_PATH: './public/upload/champcompany/',
    COMPANY_LOGIN_REPORT: './public/upload/reports/company/',
    COMPANY_LOGIN_AGREEMENT_REPORT: './public/upload/reports/agreement/company/',
    COMPANY_COVID19_REPORT: './public/upload/reports/covid/company/',
    COMPANY_BILLBOARD_REPORT: './public/upload/billboard-report/',
    COMPANY_REIMBURSMENT_REPORT: './public/upload/reports/reimbursment/company/',
    COMPANY_ACTIVITY_REPORT: './public/upload/reports/activity/company/',
    COMPANY_SURVEY_REPORT: './public/upload/reports/survey/company/',
    COMPANY_HEALTH_TOBACCO_REPORT: './public/upload/reports/health/tobacco/company/',
    COMPANY_HEALTH_HIPPA_REPORT: './public/upload/reports/health/hippa/company/',
    COMPANY_HEALTH_AGE_GENDER_REPORT: './public/upload/reports/health/agegender/company/',
    COMPANY_HEALTH_PARTICIPATION_REPORT: './public/upload/reports/health/participation/company/',
    COMPANY_HEALTH_INDIVIDUAL_REPORT: './public/upload/reports/health/individual/company/',
    COMPANY_HEALTH_QUESTIONNAIRE_REPORT: './public/upload/reports/health/questionnaire/company/',
    COMPANY_HEALTH_ENGAGEMENT_REPORT: './public/upload/reports/health/engagement/company/',
    COMPANY_QUICKLINK_REPORT: './public/upload/reports/quicklink/company/',
    COMPANY_FOD_REPORT: './public/upload/reports/fod/company/',
    COMPANY_EWB_REPORT: './public/upload/reports/ewb/company/',
    COMPANY_QUIZ_REPORT: './public/upload/reports/quiz/company/',
    COMPANY_CHALLENGE_REPORT: './public/upload/reports/challenge/company/',
    COMPANY_INCENTIVE_REPORT: './public/upload/reports/incentive/company/',
    COMPANY_CAMPAIGN_REPORT: './public/upload/reports/campaign/company/',
    COMPANY_CENSUS_DETAILS_REPORT: './public/upload/reports/OrgcensusReport/company/',
    COMPANY_INFO_LOGO_PATH: './public/upload/company/infologo',
    WELLBEING_PATH: './public/upload/wellbeing/',
    USER_IMAGE_PATH: './public/upload/user/',
    FITNESS_IMAGE_PATH: './public/upload/fitness/',
    COMPANY_DASHBOARD: './public/upload/dashboard/',
    COMPANY_EMAIL_ATTACHMENT: './public/upload/email_attachment/',
    ACTIVITY_TRACKER_IMAGE_PATH: './public/upload/activity_tracker/',
    REIMBURSEMENT_IMAGE_PATH: './public/upload/reimbursement/',
    HEALTH_CHECKUP_IMAGE_PATH: './public/upload/health_checkup/',
    HEALTH_CHECKUP_ZIP_PATH: './public/upload/health_checkup_zip/',
    CATEGORY_ICON_IMAGE_PATH: './public/upload/category_icon/',
    QUIZ_ICON_IMAGE_PATH: './public/upload/quiz/',
    PLANS_ICON_IMAGE_PATH: './public/upload/my_plan/plans/',
    SSO_FILE_PATH: './public/upload/sso/',
    ACTIVITY_ICON_IMAGE_PATH: './public/upload/my_plan/activity/',
    COMPLETE_ACTIVITY_IMAGE_PATH: './public/upload/my_plan/complete_activity/',
    COMPLETE_ACTIVITY_FILE_PATH: './public/upload/my_plan/complete_activity/',
    BLOCKS_ICON_IMAGE_PATH: './public/upload/my_plan/blocks/',
    CHALLENGE_IMAGE_PATH: './public/upload/challenge/',
    CHALLENGE_SIGNATURE_PATH: './public/upload/challenge/signature/',
    CENSUS_FILE_PATH: './public/userimport/',
    ONBOARD_CENSUS_FILE_PATH: './public/userimport/onboarding/',
    CUSTOM_POINT_REQUEST_PATH: './public/upload/custom_point_request/',
    HEALTH_REQUEST_PATH: './public/upload/health_request/',
    EMOTIONAL_WELL_BEING_JSON_PATH: './public/upload/emotional_well_being/json/',
    DOCUMENT: './public/upload/DOCUMENT/',
    TRANSLATION: './public/upload/translation/',
    UPLOAD_PATH: 'public/images',
    COMUNICATION_CAMPAIGN_FILE_TEMP_PATH: './public/upload/emailcampaignfile',
    COMUNICATION_CAMPAIGN_FILE_PATH: './public/upload/emailcampaignfile/campaign_import_files',
    COMMUNICATION_ASSETS_TEMP_PATH: './public/upload/assets',
    COVID_ASSETS_TEMP_PATH: './public/upload/covid',
    QUIZ_DEFAULTS_PATH: './public/upload/quiz_defaults',
    CUSTOM_POINT_REQUEST_FILE_PATH: './public/upload/custom_point_request',
    CHALLENGE_USER_UPLOAD_FILE_PATH: './public/upload/challenge_user_upload',
    MY_PLAN_REPORT_FILE_PATH: './public/upload/my_plan/report',
    ANNUAL_REPORT_FILE_PATH: './public/upload/annual_report',
    MARKETING_CAREER_PATH: './public/upload/marketing_career/',
    ATOLOGIST_CAREER_PATH: './public/upload/atologist_career/',
    TEMPLATE_IMAGE_PATH: './public/templateImage/common/',
    LANG_TRANSLATION_PATH: './public/upload/lang_translation/common/',
    ERROR_RPORTING_PATH: './public/error_reporting/',
    BASE_URL: process.env.BASE_URL,
    WEB_URL: process.env.WEB_URL,
    FILE_SIZE: 5 * 1024 * 1024,
    FILE_SIZE_2MB: 2 * 1024 * 1024,
    FILE_SIZE_10MB: 10 * 1024 * 1024,
    FILE_SIZE_100MB: 100 * 1024 * 1024,
    FILE_SIZE_1MB: 1 * 1024 * 1024,
    RATE_LIMIT: process.env.RATE_LIMIT,
    FILE_UPLOAD_RATE_LIMIT: process.env.FILE_UPLOAD_RATE_LIMIT,
    ADMIN_ROLE: [1, 8, 19, 20, 25, 37, 38, 39, 41, 42, 43],
    EXCLUDE_TIMEZONE_ROLE: [7, 18, 19, 20, 22, 23, 25, 35, 36, 37, 38, 39, 40, 41],
    ROLE: {
        "ADMIN": 1,
        "REGISTERED": 2,
        "ORGADMIN": 11,
        "PUBLIC": 3,
        "BROKER": 7,
        "PHYSICIAN": 8,
        "WCH": 12,
        "MGR": 13,
        "OPPSADMIN": 15,
        "SPOUSE": 16,
        "OTHER": 17,
        "SUPPORT_LEVEL_1": 18,
        "GLOBALCOACH": 19,
        "COACH": 20,
        "BROKERADMIN": 22,
        "REGIONALADMIN": 23,
        "DATAMANAGER": 25,
        "CENSUSGLOBALADMIN": 35,
        "CENSUSADMIN": 36,
        "GLOBALDATAMANAGER": 37,
        "GLOBALMARKETINGMANAGER": 38,
        "MARKETINGMANAGER": 39,
        "ENGAGEMENTDATAMANAGER": 40,
        "NEWSLETTERDESIGNER": 41,
        "CLIENTENGAGEMENTMANAGER": 42,
        "GLOBALCLIENTENGAGEMENTMANAGER": 43,
    },
    DEFAULT_HEADER: {
        'A': 'Department',
        'B': 'Status',
        'C': 'Relationship Code',
        'D': 'Relationship ID',
        'E': 'User Type',
        'F': 'ID of Direct Supervisor',
        'G': 'User Name',
        'H': 'First Name',
        'I': 'Middle Name',
        'J': 'Last Name',
        'K': 'Job Title',
        'L': 'SSN',
        'M': 'Employee ID',
        'N': 'Gender',
        'O': 'Birth Date',
        'P': 'Date of Hire',
        'Q': 'On Health Plan',
        'R': 'Health Plan Name',
        'S': 'Email',
        'T': 'Work Phone Number',
        'U': 'Work Phone Extension',
        'V': 'Location',
        'W': 'WorkAddress 1',
        'X': 'WorkAddress 2',
        'Y': 'Work City',
        'Z': 'Work State/Province',
        'AA': 'Work Zip/Postal Code',
        'AB': 'Work Country',
        'AC': 'Home Phone Number',
        'AD': 'Mobile Phone Number',
        'AE': 'HomeAddress 1',
        'AF': 'HomeAddress 2',
        'AG': 'Home City',
        'AH': 'Home State/Province',
        'AI': 'Home Zip/Postal Code',
        'AJ': 'Home Country',
        'AK': 'User Code',
        'AL': 'Eligible For Campaign',
        'AM': 'Unsubscribe',
        'AN': 'Lock Email',
    },
    SPOUSE_DEFAULT_HEADER: {
        "BA": "Spouse First Name",
        "BB": "Spouse Last Name",
        "BC": "Spouse DOB",
        "BD": "Spouse Gender",
        "BE": "Spouse Email",
        "BF": "Spouse On Health Plan",
        "BG": "Spouse Health Plan name"
    },
    HEALTH_FORM_DEFAULT_DATA: {
        '1': 'Physician Visit Form',
        '2': 'Dental Visit Form',
        '3': 'Optometry/ Ophthalmology Visit Form',
        '4': 'Tobacco Affidavit',
        '5': 'Biometric Screening Form',
        '6': 'Age/Gender Preventive Screening Form'
    },
    DATABASE_HEADER: {
        'A': 'department_id',
        'B': 'user_status',
        'C': 'relationship_code',
        'D': 'relationship_id',
        'E': 'role_id',
        'F': 'supervisor_id',
        'G': 'username',
        'H': 'first_name',
        'I': 'middle_name',
        'J': 'last_name',
        'K': 'jobtitle',
        'L': 'securitycode',
        'M': 'employeeid',
        'N': 'gender',
        'O': 'dob',
        'P': 'date_of_hire',
        'Q': 'on_insurance_plan',
        'R': 'insurance_plan_name',
        'S': 'email',
        'T': 'wphone',
        'U': 'wphone_ext',
        'V': 'location',
        'AC': 'hphone',
        'AD': 'cphone',
        'AE': 'address',
        'AF': 'address2',
        'AG': 'city',
        'AH': 'state',
        'AI': 'zip',
        'AJ': 'country',
        'AK': 'code',
        'AL': 'is_camp_eligible'
    },
    USER_TYPE: ['16', 'spouse', 'domestic partner', 'spouse / domestic partner'],
    DEFAULT_IMAGE: {
        USER: `${process.env.BASE_URL}/upload/placeholder/user-no-image.png`,
    },
    JWT: {
        SECRET_KEY: process.env.SECRET_KEY_PROD,
        EXPIRES_IN: process.env.JWT_EXPIRE_PROD,
        SECURITY_SALT: process.env.SECURITY_SALT_ROUND_PROD,
    },
    PLUGINS: ['Activity', 'Activitytracker', 'Automaticreport', 'Biometricresult', 'Census', 'Challenge', 'Chat', 'Claim', 'Coach', 'Communication', 'Companies', 'Covid', 'Deviceconfigurations', 'Diseasemanagement', 'Documentmanagement', 'Dynamictext', 'Emotionalwellbeing', 'Events', 'Exercise', 'Healthcheckup', 'Hra', 'Incentive', 'Internalmail', 'Languagetext', 'Media', 'Myplan', 'Plannutrition', 'Quicklink', 'Quiz', 'Reimbursements', 'Sidebar', 'Themes', 'Trackers', 'Upcomingactivities', 'Users'],
    DEFAULT_PLUGINS:{ Themes: 1, Users: 1, Companies: 1, Census: 1 },
    BROKER_AND_HEALTH_ORG_PLUGINS:{"Themes":1,"Users":1,"Companies":1,"Census":1,"Activity":1,"Hra":1,"Healthcheckup":1,"Quicklink":1,"Incentive":1,"Documentmanagement":1,"Sidebar":1,"Automaticreport":1,"Challenge":1,"Events":1,"Trackers":1,"Upcomingactivities":1,"Activitytracker":1,"Quiz":1,"Emotionalwellbeing":1,"Myplan":1,"Media":1,"Covid":1,"Reimbursements":1,"Diseasemanagement":1},
    RECORD_PER_PAGE: 10,
    TRANSLATIONS_DIR: './src/local',
    PERMISSIONS_DIR: './src/local/data.encrypted',
    TRANSLATIONS_FILE: 'data.json',
    DEVICE: {
        1: "Garmin",
        3: "Jawbone",
        4: "Withings",
        5: "Google Fit",
        6: "Misfit"
    },
    SIDEMENUSETTING: {
        'Dashboard': '',
        'Enable_Dashboard': '1',
        'Agreement': '',
        "Enable_Agreement": "1",
        'Activities': '',
        "Enable_Activities": "1",
        'Activity_Forms': '',
        "Enable_Activity_Forms": "1",
        'Activity_Forms_Submit_Form': '',
        "Enable_Activity_Forms_Submit_Form": "1",
        'Activity_Forms_Submitted_Forms': '',
        "Enable_Activity_Forms_Submitted_Forms": "1",
        'Reimbursements': '',
        "Enable_Reimbursements": "1",
        'Reimbursements_Submit_Form': '',
        "Enable_Reimbursements_Submit_Form": "1",
        'Reimbursements_Submitted_Forms': '',
        "Enable_Reimbursements_Submitted_Forms": "1",
        'Health_Forms': '',
        "Enable_Health_Forms": "1",
        'Health_Forms_Submit_Forms': '',
        "Enable_Health_Forms_Submit_Forms": "1",
        'Health_Forms_Submitted_Forms': '',
        "Enable_Health_Forms_Submitted_Forms": "1",
        'Devices_Sync': '',
        "Enable_Devices_Sync": "1",
        'Devices_Sync_Devices_Sync': '',
        "Enable_Devices_Sync_Devices_Sync": "1",
        'My_Health': '',
        "Enable_My_Health": "1",
        'My_Health_Assessment': '',
        "Enable_My_Health_Assessment": "1",
        'My_Health_Health_Data': '',
        "Enable_My_Health_Health_Data": "1",
        'My_Health_Results': '',
        "Enable_My_Health_Results": "1",
        'Plans': '',
        "Enable_Plans": "1",
        'Trackers': '',
        "Enable_Trackers": "1",
        'Trackers_Nutrition': '',
        "Enable_Trackers_Nutrition": "1",
        'Trackers_Exercise': '',
        "Enable_Trackers_Exercise": "1",
        'Trackers_Measurements': '',
        "Enable_Trackers_Measurements": "1",
        'Trackers_Biometrics': '',
        "Enable_Trackers_Biometrics": "1",
        'Trackers_Fitbit_Sync': '',
        "Enable_Trackers_Fitbit_Sync": "1",
        'Trackers_Covid_Passport': '',
        "Enable_Trackers_Covid_Passport": "1",
        'Events': '',
        "Enable_Events": "1",
        'Challenges': '',
        "Enable_Challenges": "1",
        'Challenges_Join_Challenges': '',
        "Enable_Challenges_Join_Challenges": "1",
        'Challenges_My_Challenges': '',
        "Enable_Challenges_My_Challenges": "1",
        'Quizzes': '',
        "Enable_Quizzes": "1",
        'Support': '',
        "Enable_Support": "1",
        'Internalmail': '',
        "Enable_Internalmail": "1",
        'Internalmail_Email': '',
        "Enable_Internalmail_Email": "1",
        'Emotional_Well-Being': '',
        "Enable_Emotional_Well-Being": "1",
        'Media': '',
        "Enable_Media": "1",
        'Media_Fitness_Videos': '',
        "Enable_Media_Fitness_Videos": "1",
        'Media_Media_Dashboard': '',
        "Enable_Media_Media_Dashboard": "1",
        'Quicklink': '',
        "Enable_Quicklink": "1",
        'Icon_Dashboard': 'fa fa-dashboard',
        'Icon_Agreement': 'fa fa-thumbs-o-up',
        'Icon_Activities': 'fa fa-check-square-o',
        'Icon_Activity_Forms': 'fa fa-th-list',
        'Icon_Reimbursements': 'fa fa-th-list',
        'Icon_Health_Forms': 'fa fa-th-list',
        'Icon_Devices_Sync': 'fa fa-exchange',
        'Icon_My_Health': 'fa fa-heart',
        'Icon_Plans': 'fa fa-compass',
        'Icon_Trackers': 'fa fa-bar-chart-o',
        'Icon_Events': 'fa fa-calendar',
        'Icon_Challenges': 'fa fa-user',
        'Icon_Quizzes': 'fa fa-question',
        'Icon_Support': 'fa fa-question-circle',
        'Icon_Internalmail': 'fa fa-map-marker',
        'Icon_Emotional_Well-Being': 'fa fa-folder',
        'Icon_Media': 'fa fa-folder',
        'Icon_Quicklink': 'fa fa-link'
    },
    MAINMENUITEMS: ['Dashboard', 'Agreement', 'Activities', 'Activity_Forms', 'Reimbursements', 'Health_Forms', 'Devices_Sync', 'My_Health', 'Plans', 'Trackers', 'Events', 'Challenges', 'Quizzes', 'Support', 'Internalmail', 'Emotional_Well-Being', 'Media', 'Quicklink'],
    SUBMENUITEMS: ['Activity_Forms_Submit_Form', 'Activity_Forms_Submitted_Forms', 'Reimbursements_Submit_Form', 'Reimbursements_Submitted_Forms', 'Health_Forms_Submit_Forms', 'Health_Forms_Submitted_Forms', 'Devices_Sync_Devices_Sync', 'My_Health_Assessment', 'My_Health_Health_Data', 'My_Health_Results', 'Trackers_Nutrition', 'Trackers_Exercise', 'Trackers_Measurements', 'Trackers_Biometrics', 'Trackers_Fitbit_Sync', 'Trackers_Covid_Passport', 'Challenges_Join_Challenges', 'Challenges_My_Challenges', 'Internalmail_Email', 'Media_Fitness_Videos', 'Media_Media_Dashboard'],
    USER_HEADERS: ["USER CODE", "ORGANIZATION", "DEPARTMENT", "RELATIONSHIP ID", "USERNAME", "FIRST NAME", "MIDDLE NAME", "LAST NAME", "JOB TITLE", "EMPLOYEE ID", "GENDER", "BIRTH DATE", "DATE OF HIRE", "ON HEALTH PLAN", "HEALTH PLAN NAME", "EMAIL", "LOCATION", "User Type"],
    FITNESS_CHALLENGE_HEADERS: ['TOTAL ACTIVITIES', 'TOTAL COMPLETED ACTIVITIES', 'TOTAL % COMPLETION','RANK'],
    OLYMPICS_CHALLENGE_HEADERS: ['WEEKLY TASKS', 'WEEKLY TASKS COMPLETED', 'TOTAL % COMPLETION','TOTAL MINUTES','NUMBER OF TIMES THAT ACTIVITY WAS INPUT','COMPLETED'],
    PREVENTATIVE_CARE_HEADERS: [
        'Breast Cancer Screen (Female-Clinical Exam by Health Care provider every 1-3 years)',
        'Cervical Cancer Screen (Female-Pap Smear for sexually active females over 21)(Age 19-39)',
        'Dental Exam(Age 19-39)',
        'Flu Vaccine (annually)',
        'Tetanus, Diphtheria, Pertussis Vaccine (every 10 years)',
        'Breast Cancer Screen (Female-Clinical Exam and Mammogram every year)(Age 40-64)',
        'Cervical Cancer Screen (Female-Pap Smear for sexually active females over 21)(Age 40-64)',
        'Prostate Cancer Screen (Male)(Age 40-64)',
        'Dental Exam(Age 40-64)',
        'Flu Vaccine(Age 40-64)',
        'Tetanus, Diphtheria, Pertussis (every 10 years)(Age 40-64)',
        'Pneumonia Vaccine (recommended for smokers and/or asthmatics)',
        'Zoster (Shingles Age 60+ single dose)(Age 40-64)',
        'Colorectal Cancer Screen (beginning at age 45)(Age 40-64)',
        'Colorectal Cancer Screen (beginning at age 40)(Age 40-64)',
        'Breast Cancer Screen (Female-Clinical Exam and Mammogram every year)(Age 65+)',
        'Cervical Cancer Screen (Female-Pap Smear, if you have had at least 3 normal pap tests in a row and no abnormal pap tests in the last 10 years, you may choose to stop screening)',
        'Dental Exam(Age 65+)',
        'Prostate Cancer Screen (Male)(Age 65+)',
        'Colorectal Cancer Screen (beginning at age 45)(Age 65+)',
        'Abdominal Aortic Aneurysm (Male-Ages 65-75 if you have ever smoked)',
        'Flu Vaccine(Age 65+)',
        'Tetanus, Diphtheria, Pertussis (every 10 years)(Age 65+)',
        'Zoster (Shingles Age 60+ single dose)(Age 65+)',
        'Annual Vision Exam(Age 19-39)',
        'Annual Vision Exam(Age 40-64)',
        'Annual Vision Exam(Age 65+)',
        'Skin Cancer Screening(Age 19-39)',
        'Skin Cancer Screening(Age 40-64)',
        'Skin Cancer Screening(Age 65+)',
        'Cardiac Stress Test(Age 40-64)',
        'Cardiac Stress Test(Age 65+)',
        'Osteoporosis Screening',
        'Breast Cancer Screening',
        'Colon Cancer Screening',
        'COVID-19 Vaccine(Age 19-39)',
        'COVID-19 Vaccine(Age 40-64)',
        'COVID-19 Vaccine(Age 65+)',
        'COVID-19 Booster Shot(Age 19-39)',
        'COVID-19 Booster Shot(Age 40-64)',
        'COVID-19 Booster Shot(Age 65+)',
        'PHQ-9(Age 19-39)',
        'PHQ-9(Age 40-64)',
        'PHQ-9(Age 65+)',
        'GAD-7(Age 19-39)',
        'GAD-7(Age 40-64)',
        'GAD-7(Age 65+)',
        'STI Screening(Age 19-39)',
        'STI Screening(Age 40-64)',
        'STI Screening(Age 65+)',
        'Shingles Vaccine(Age 19-39)',
        'Shingles Vaccine(Age 40-64)',
        'Shingles Vaccine(Age 65+)',
        'HPV Vaccine (up to age 45)(Age 19-39)',
        'HPV Vaccine (up to age 45)(Age 40-64)',
        'RSV Vaccine (starting at age 60)',
        'Lung Cancer Screening (starting at age 50, former or current smokers)',
        'RSV Vaccine',
        'Lung Cancer Screening (former or current smokers)',
        'Annual Wellness Visit(Age 19-39)',
        'Annual Wellness Visit(Age 40-64)',
        'Annual Wellness Visit(Age 65+)',
        'Cholesterol Test(Age 19-39)',
        'Cholesterol Test(Age 40-64)',
        'Cholesterol Test(Age 65+)',
        'Lipid Profile(Age 19-39)',
        'Lipid Profile(Age 40-64)',
        'Lipid Profile(Age 65+)',
        'Bone Density Test (Female)(Age 65+)',
        'Cologuard (Age 45+)',
        'Cervical Cancer Screen (Females Age 25+)(Age 19-39)',
        'Cervical Cancer Screen (Females Age 25+)(Age 40-64)',
        'Cervical Cancer Screen (Females Age 25+)(Age 65+)',
        'Prostate Cancer Screen (Male Age 50+)(Age 40-64)',
        'Prostate Cancer Screen (Male Age 50+)(Age 65+)',
        'Well-Woman Visit (Females)(Age 19-39)',
        'Well-Woman Visit (Females)(Age 40-64)',
        'Well-Woman Visit (Females)(Age 65+)',
        'Hearing (Age 19-39)',
        'Hearing (Age 40-64)',
        'Hearing (Age 65+)',
        'Nutrition Counseling (Age 19-39)',
        'Nutrition Counseling (Age 40-64)',
        'Nutrition Counseling (Age 65+)',
        'Mental Health/Behavioral Health Screening (Age 19-39)',
        'Mental Health/Behavioral Health Screening (Age 40-64)',
        'Mental Health/Behavioral Health Screening (Age 65+)',
        'Source- Entered by',
        'Created Date',
        'Inserted Date'
    ],
    CARE_FIELDS: [
        {'1' : 'Breast Cancer Screen (Female-Clinical Exam by Health Care provider every 1-3 years)'},
        {'2' : 'Cervical Cancer Screen (Female-Pap Smear for sexually active females over 21)(Age 19-39)'},
        {'3' : 'Dental Exam(Age 19-39)'},
        {'4' : 'Flu Vaccine (annually)'},
        {'5' : 'Tetanus, Diphtheria, Pertussis Vaccine (every 10 years)'},
        {'6' : 'Breast Cancer Screen (Female-Clinical Exam and Mammogram every year)(Age 40-64)'},
        {'7' : 'Cervical Cancer Screen (Female-Pap Smear for sexually active females over 21)(Age 40-64)'},
        {'8' : 'Prostate Cancer Screen (Male)(Age 40-64)'},
        {'9' : 'Dental Exam(Age 40-64)'},
        {'10' : 'Flu Vaccine(Age 40-64)'},
        {'11' : 'Tetanus, Diphtheria, Pertussis (every 10 years)(Age 40-64)'},
        {'12' : 'Pneumonia Vaccine (recommended for smokers and/or asthmatics)'},
        {'13' : 'Zoster (Shingles Age 60+ single dose)(Age 40-64)'},
        {'14' : 'Colorectal Cancer Screen (beginning at age 45)(Age 40-64)'},
        {'38' : 'Colorectal Cancer Screen (beginning at age 40)(Age 40-64)'},
        {'15' : 'Breast Cancer Screen (Female-Clinical Exam and Mammogram every year)(Age 65+)'},
        {'16' : 'Cervical Cancer Screen (Female-Pap Smear, if you have had at least 3 normal pap tests in a row and no abnormal pap tests in the last 10 years, you may choose to stop screening)'},
        {'17' : 'Dental Exam(Age 65+)'},
        {'18' : 'Prostate Cancer Screen (Male)(Age 65+)'},
        {'19' : 'Colorectal Cancer Screen (beginning at age 45)(Age 65+)'},
        {'20' : 'Abdominal Aortic Aneurysm (Male-Ages 65-75 if you have ever smoked)'},
        {'21' : 'Flu Vaccine(Age 65+)'},
        {'22' : 'Tetanus, Diphtheria, Pertussis (every 10 years)(Age 65+)'},
        {'23' : 'Zoster (Shingles Age 60+ single dose)(Age 65+)'},
        {'24' : 'Annual Vision Exam(Age 19-39)'},
        {'25' : 'Annual Vision Exam(Age 40-64)'},
        {'26' : 'Annual Vision Exam(Age 65+)'},
        {'27' : 'Skin Cancer Screening(Age 19-39)'},
        {'28' : 'Skin Cancer Screening(Age 40-64)'},
        {'29' : 'Skin Cancer Screening(Age 65+)'},
        {'30' : 'Cardiac Stress Test(Age 40-64)'},
        {'31' : 'Cardiac Stress Test(Age 65+)'},
        {'32' : 'Osteoporosis Screening'},
        {'33' : 'Breast Cancer Screening'},
        {'34' : 'Colon Cancer Screening'},
        {'35' : 'COVID-19 Vaccine(Age 19-39)'},
        {'36' : 'COVID-19 Vaccine(Age 40-64)'},
        {'37' : 'COVID-19 Vaccine(Age 65+)'},
        {'51' : 'COVID-19 Booster Shot(Age 19-39)'},
        {'52' : 'COVID-19 Booster Shot(Age 40-64)'},
        {'53' : 'COVID-19 Booster Shot(Age 65+)'},
        {'81' : 'PHQ-9(Age 19-39)'},
        {'82' : 'PHQ-9(Age 40-64)'},
        {'83' : 'PHQ-9(Age 65+)'},
        {'85' : 'GAD-7(Age 19-39)'},
        {'86' : 'GAD-7(Age 40-64)'},
        {'87' : 'GAD-7(Age 65+)'},
        {'71' : 'STI Screening(Age 19-39)'},
        {'72' : 'STI Screening(Age 40-64)'},
        {'73' : 'STI Screening(Age 65+)'},
        {'74' : 'Shingles Vaccine(Age 19-39)'},
        {'75' : 'Shingles Vaccine(Age 40-64)'},
        {'76' : 'Shingles Vaccine(Age 65+)'},
        {'88' : 'HPV Vaccine (up to age 45)(Age 19-39)'},
        {'89' : 'HPV Vaccine (up to age 45)(Age 40-64)'},
        {'90' : 'RSV Vaccine (starting at age 60)'},
        {'91' : 'Lung Cancer Screening (starting at age 50, former or current smokers)'},
        {'92' : 'RSV Vaccine'},
        {'93' : 'Lung Cancer Screening (former or current smokers)'},
        {'94' : 'Annual Wellness Visit(Age 19-39)'},
        {'95' : 'Annual Wellness Visit(Age 40-64)'},
        {'96' : 'Annual Wellness Visit(Age 65+)'},
        {'97' : 'Cholesterol Test(Age 19-39)'},
        {'98' : 'Cholesterol Test(Age 40-64)'},
        {'99' : 'Cholesterol Test(Age 65+)'},
        {'100' : 'Lipid Profile(Age 19-39)'},
        {'101' : 'Lipid Profile(Age 40-64)'},
        {'102' : 'Lipid Profile(Age 65+)'},
        {'103' : 'Bone Density Test (Female)(Age 65+)'},
        {'104' : 'Cologuard (Age 45+)'},
        {'105' : 'Cervical Cancer Screen (Females Age 25+)(Age 19-39)'},
        {'106' : 'Cervical Cancer Screen (Females Age 25+)(Age 40-64)'},
        {'107' : 'Cervical Cancer Screen (Females Age 25+)(Age 65+)'},
        {'108' : 'Prostate Cancer Screen (Male Age 50+)(Age 40-64)'},
        {'109' : 'Prostate Cancer Screen (Male Age 50+)(Age 65+)'},
        {'110' : 'Well-Woman Visit (Females)(Age 19-39)'},
        {'111' : 'Well-Woman Visit (Females)(Age 40-64)'},
        {'112' : 'Well-Woman Visit (Females)(Age 65+)'},
        {'113' : 'Hearing (Age 19-39)'},
        {'114' : 'Hearing (Age 40-64)'},
        {'115' : 'Hearing (Age 65+)'},
        {'116' : 'Nutrition Counseling (Age 19-39)'},
        {'117' : 'Nutrition Counseling (Age 40-64)'},
        {'118' : 'Nutrition Counseling (Age 65+)'},
        {'119' : 'Mental Health/Behavioral Health Screening (Age 19-39)'},
        {'120' : 'Mental Health/Behavioral Health Screening (Age 40-64)'},
        {'121' : 'Mental Health/Behavioral Health Screening (Age 65+)'},
    ],
    HRA_DETAIL_HEADERS: ["Overall Score", "Current Health Section Score", "Current Health Risk Level", "Prevention Section Score", "Prevention Risk Level", "Nutrition Section Score", "Nutrition Risk Level", "Exercise Section Score", "Exercise Risk Level", "Emotional Health Section Score", "Emotional Health Risk Level"],
    HRA_BIOMETRICS_HEADERS: ["HRA Taken Date", "Height", "Weight", "BMI", "BMI Risk Level", "Blood Pressure - Systolic", "Blood Pressure - Systolic Risk Level", "Blood Pressure - Diastolic", "Blood Pressure - Diastolic Risk Level", "Blood Glucose", "Blood Glucose Risk Level", "Test Type", "A1C", "A1C Risk Level", "HDL", "HDL Risk Level", "LDL", "LDL Risk Level", "Total Cholesterol", "Total Cholesterol Risk Level", "Triglycerides", "Triglycerides Risk Level", "Waist", "Waist Risk Level", "Source - Entered By", "Biometric Date", "Entered Date", "Tobacco User"],
    TOBACCO_STATUS: {'0':'','1' : 'I am tobacco-free', '2':'I am tobacco user', '3':'I am tobacco user and is currently under my care for tobacco cessation'},
    TOBACCO_PHYSICIAN_STATUS: {'0':'','1' : 'My patient is tobacco-free', '2':'My patient is a tobacco user', '3':'My patient is a tobacco user and is currently under my care for tobacco cessation'},
    FOOD_ACTIVITY_DATA: {
        'Walk': {type: 'Activity Tracker- Walking', typeId: 15, stepsMultiplier: 2112},
        'Walking': {type: 'Activity Tracker- Walking', typeId: 15, stepsMultiplier: 2112},
        'Run': {type: 'Activity Tracker- Running', typeId: 16, stepsMultiplier: 2112},
        'Running': {type: 'Activity Tracker- Running', typeId: 16, stepsMultiplier: 2112},
        'Cycling': {type: 'Activity Tracker- Cycling', typeId: 17, stepsMultiplier: 1147.86},
        'Swimming': {type: 'Activity Tracker- Swimming', typeId: 18, stepsMultiplier: 2112},
        'default': {type: 'Activity Tracker', typeId: 7, stepsMultiplier: 2112}
    },
    BODYFATCHARTDATA: [
        {
            Classification: 'Essential Fat',
            Women: '10-12%',
            Men: '2-4%',
        },
        {
            Classification: 'Athletes',
            Women: '14-20%',
            Men: '6-13%',
        },
        {
            Classification: 'Fitness',
            Women: '21-24%',
            Men: '14-17%',
        },
        {
            Classification: 'Acceptable',
            Women: '25-31%',
            Men: '18-25%',
        },
        {
            Classification: 'Obese',
            Women: '32% plus',
            Men: '25% plus',
        },
    ],
    HTML_ENTITIES: {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        "'": '&#39;',
        '"': '&quot;',
        '!': '&#33;',
        '@': '&#64;',
        '$': '&#36;',
        '%': '&#37;',
        '(': '&#40;',
        ')': '&#41;',
        '=': '&#61;',
        '+': '&#43;',
        '{': '&#123;',
        '}': '&#125;',
    },
    EVENT_NAME: {
        0: "Custom",
        1: "Event",
        2: "EHA",
        3: "Age/Gender Appropriate Preventive Screening",
        4: "Challenge",
        5: "Quicklink",
        6: "Quiz",
        7: "HRA",
        8: "Biometric",
        9: "Emotional Well-Being"
    },
    BIO_DATA: {
        1: "Height",
        2: "Weight",
        3: "BMI",
        4: "Systolic",
        5: "Diastolic",
        6: "Random Blood Glucose",
        7: "A1C",
        8: "Total Cholesterol",
        9: "HDL Cholesterol",
        10: "LDL Cholesterol",
        11: "Triglycerides",
        12: "Waist Circumference",
        13: "HRA - Current Health",
        14: "HRA - Prevention",
        15: "HRA - Nutrition",
        16: "HRA - Exercise",
        17: "HRA - Emotional Health",
        19: "Tobacco Affidavit",
        20: "Physician form",
        21: "Dental form",
        22: "Optimetric form",
        25: "Org Specific",
        26: "Fasting Blood Glucose",
        30: "Online Health Assessment"
    },
    /* Note: alc is a1c but database field alc so a1c -> alc add here (optimize) */
    BIO_DATA_LIST: {
        1: 'height',
        2: 'weight',
        3: 'bmi',
        4: 'systolic',
        5: 'diastolic',
        6: 'random_blood_glucose',
        7: 'alc',
        8: 'total_cholesterol',
        9: 'hdl',
        10: 'ldl',
        11: 'triglycerides',
        12: 'waist',
        26: 'fasting_blood_glucose'
    },
    MODULE_DATA: {
        1: "Events",
        2: "EHA",
        3: "Age/Gender Appropriate Preventive Screening",
        4: "Challenges",
        5: "Quicklink",
        6: "Quiz",
        7: "HRA",
        8: "Biometric",
        9: "Emotional Well-Being"
    },
    HRA_DATA: {1: 'Current Health', 2: 'Prevention', 3: 'Nutrition', 4: 'Exercise', 5: 'Emotional Health'},
    CUSTOM_COMPLETION_DATA: ["Organization", "User Id", "Department", "First Name", "Middle Name", "Last Name", "Role type", "Job Title", "Employee ID", "DOB", "On Health Plan", "Email", "Work Phone Number", "Home Phone Number", "Location", "Work Address 1", "Work Address 2", "Work City", "Work State/Province", "Work Country", "Work Zip/Postal Code"],
    GENDER_MAP: {'m': 1, 'male': 1, 'f': 2, 'female': 2, 'o': 3, 'other': 3},
    OPTION_LEVEL: {'0': 'Low', '1': 'Medium', '2': 'High', '3': 'Moderate', '4': 'Very high'},
    RANGE_TYPE_OPTIONS: {0: 'Equal to', 1: 'Greater than', 2: 'Greater than or Equal to', 3: 'Less than', 4: 'Less than or Equal to', 5: 'Range'},
    QUESTION_TYPE: {1: 'Question', 2: 'Heading Text', 3: 'Sub Heading Text', 4: 'Text'},
    DATE_COLUMNS: ['dob', 'doh', 'created', 'updated', 'created_date', 'modified_date', 'added_date', 'updated_date', 'update_date', 'start_date', 'end_date', 'date', 'fax_date',
        'modified', 'startdate', 'enddate', 'update', 'add_date', 'datetime', 'date_of_service', 'birth_date', 'due_date', 'date_time', 'reminder_date',
        'activity_date', 'is_hire_date', 'test1_start_date', 'test1_end_date', 'test2_start_date', 'test2_end_date', 'act_date', 'submission_date', 'inserted',
        'd_start_date', 'd_end_date', 'point_end_date', 'after_deadline_date', 'request_date', 'start_date_range', 'end_date_range', 'date_completed',
        'reg_start_date', 'reg_end_date', 'deactive_date', 'rangestartdate', 'rangeenddate', 's_rangestartdate', 's_rangeenddate', 'baton_start', 'slotdate',
        'contract_start_date', 'contract_end_date','billing_start_date', 'billing_end_date', 'date_of_expense_submission', 'from_date', 'to_date', 'physician_date', 'lastvaccinationdate',
        'registration_date', 'heightdate', 'weightdate', 'diastolicdate', 'bloodglucosedate', 'a1cdate', 'hdldate', 'ldldate', 'total_cholesteroldate',
        'triglyceridedate', 'waistdate', 'date_obtain', 'fromdate', 'todate', 'timestamp', 'collectionDate', 'logDate', 'date_of_hire', 'logout_time', 'logout_time',
        'pf_start_date', 'pf_end_date', 'pf_fax_date', 'ta_start_date', 'ta_end_date', 'ta_fax_date', 'dvf_start_date', 'dvf_end_date', 'dvf_fax_date', 'otp_created',
        'ovf_start_date', 'ovf_end_date', 'ovf_fax_date', 'feature_hra_date', 'reset_date', 'feature_fax_date', 'feature_end_date', 'feature_start_date',
        'ta_reset_date', 'feture_ta_fax_date', 'feture_ta_end_date', 'feture_ta_start_date', 'ovf_reset_date', 'feture_ovf_fax_date', 'feture_ovf_end_date',
        'feture_ovf_start_date', 'dvf_reset_date', 'feture_dvf_faxt_date', 'feture_dvf_end_date', 'feture_dvf_start_date', 'pf_reset_date', 'feture_pf_fax_date',
        'feture_pf_end_date', 'feture_pf_start_date', 'c_start_date', 'c_end_date', 'attend_date','auto_remove_date','plugin_install_date','plugin_activate_date',
        'backdating_frequency','ooo_start_date','ooo_end_date','lastreportdate', 'test1_start_date', 'test1_end_date', 'test2_start_date', 'test2_end_date'
    ],
    HEADER_DATA: {'A': 'Department', 'B': 'Status', 'C': 'Relationship Code', 'D': 'Relationship ID', 'E': 'User Type', 'F': 'ID of Direct Supervisor', 'G': 'User Name', 'H': 'First Name', 'I': 'Middle Name', 'J': 'Last Name', 'K': 'Job Title', 'L': 'Social Security Number', 'M': 'Employee ID', 'N': 'Gender', 'O': 'Birth Date', 'P': 'Date of Hire', 'Q': 'On Health Plan', 'R': 'Health Plan Name', 'S': 'Email', 'T': 'Work Phone Number', 'U': 'Work Phone Extension', 'V': 'Location', 'W': 'Work Address 1', 'X': 'Work Address 2', 'Y': 'Work City', 'Z': 'Work State/Province', 'AA': 'Work Zip/Postal Code', 'AB': 'Work Country', 'AC': 'Home Phone Number', 'AD': 'Mobile Phone Number', 'AE': 'Home Address 1', 'AF': 'Home Address 2', 'AG': 'Home City', 'AH': 'Home State/Province', 'AI': 'Home Zip/Postal Code', 'AJ': 'Home Country', 'AK': 'User Code', 'AL': 'Eligible For Campaign','AM': 'Unsubscribe', 'AN': 'Lock Email'},
    GENERAL_HEADER_DATA: {'A': 'Department', 'B': 'Status', 'C': 'Relationship Code', 'D': 'Relationship ID', 'E': 'User Type', 'F': 'ID of Direct Supervisor', 'G': 'User Name', 'H': 'First Name', 'I': 'Middle Name', 'J': 'Last Name', 'K': 'Job Title', 'L': 'Social Security Number', 'M': 'Employee ID', 'N': 'Gender', 'O': 'Birth Date', 'P': 'Date of Hire', 'Q': 'On Health Plan', 'R': 'Health Plan Name', 'S': 'Email', 'T': 'Work Phone Number', 'U': 'Work Phone Extension', 'V': 'Location', 'W': 'Work Address 1', 'X': 'Work Address 2', 'Y': 'Work City', 'Z': 'Work State/Province', 'AA': 'Work Zip/Postal Code', 'AB': 'Work Country', 'AC': 'Home Phone Number', 'AD': 'Mobile Phone Number', 'AE': 'Home Address 1', 'AF': 'Home Address 2', 'AG': 'Home City', 'AH': 'Home State/Province', 'AI': 'Home Zip/Postal Code', 'AJ': 'Home Country', 'AK': 'User Code', 'AL': 'Eligible For Campaign'},
    UPLOAD_POINT_HEADER: { 0: 'Organization', 1: 'User Id', 2: 'User Code', 3: 'Username', 4: 'Department', 5: 'First Name', 6: 'Middle Name', 7: 'Last Name', 8: 'Role type', 9: 'Job Title', 10: 'Employee ID', 11: 'DOB', 12: 'On Health Plan', /*'On Current Census',*/ 13: 'Email', 14: 'Work Phone Number', 15: 'Home Phone Number', 16: 'Location', 17: 'Work Address 1', 18: 'Work Address 2', 19: 'Work City', 20: 'Work State/Province', 21: 'Work Zip/Postal Code', 22: 'Work Country' },
    UPLOAD_POINT_HEADER_DATA: {A: 'Organization', B: 'User Id', C: 'User Code', D: 'Username', E: 'Department', F: 'First Name', G: 'Middle Name', H: 'Last Name', I: 'Role type', J: 'Job Title', K: 'Employee ID', L: 'DOB', M: 'On Health Plan', N: 'Email', O: 'Work Phone Number', P: 'Home Phone Number', Q: 'Location', R: 'Work Address 1', S: 'Work Address 2', T: 'Work City', U: 'Work State/Province', V: 'Work Zip/Postal Code', W: 'Work Country'},
    SPOUSE_HEADER_DATA: {'BA': 'Spouse First Name', 'BB': 'Spouse Last Name', 'BC': 'Spouse DOB', 'BD': 'Spouse Gender', 'BE': 'Spouse Email', 'BF': 'Spouse On Health Plan', 'BG': 'Spouse Health Plan name'},
    LINKED_HEADER_DATA: { 'CA': 'Linked Emp Id'},
    CHALLENE_IMPORT_USER_HEADER: { 0: 'Organization', 1: 'User Id', 2: 'Department', 3: 'First Name', 4: 'Middle Name', 5: 'Last Name', 6: 'Job Title', 7: 'Employee ID', 8: 'DOB', 9: 'On Health Plan', 10: 'On Current Census', 11: 'Email', 12: 'Work Phone Number', /*'On Current Census',*/ 13: 'Home Phone Number', 14: 'Location', 15: 'Work Address 1', 16: 'Work Address 2', 17: 'Work City', 18: 'Work State/Province', 19: 'Work Country', 20: 'Work Zip/Postal Code' },
    CAMPAIGN_CHECK_ACTIVITIES: {
        CUSTOM_WITHOUT_TIMEZONE_CHECK_IDS: [11, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 58, 80, 127, 128, 129, 130, 131, 3810, 3811, 8427, 8461, 8495],
        TBL_HC_BIOMETRICS_IDS: [2, 4, 14, 15, 16, 17, 18, 19, 20, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46, 47, 48, 80, 126, 127, 128, 129, 3810, 3811, 6173, 8281, 8784, 9360, 10822, 12197, 12461, 12462, 12463],
        TBL_HC_DENTISTS_IDS: [40, 49],
        TBL_HC_OPTOMETRISTS_IDS: [41, 50],
        TBL_HC_TOBACCO_USES_IDS: [4, 12, 13, 14, 20],
        TBL_HC_AUTHORIZATIONS_IDS: [2, 3, 5],
        TBL_HA_ASSESSMENTS_IDS: [1, 58],
        TBL_HA_EMOTIONAL_ASSESSMENTS_IDS: [1],
        TBL_HA_HRA_BIOMETRICS_IDS: [33, 38, 39, 34, 35, 36, 37, 52, 53, 54, 55, 57, 56, 51, 21, 22, 23, 25, 26, 27, 28, 29, 30],
        TBL_HA_HRA_CONVERT_TIME : [52, 53, 54, 55, 57, 56, 51, 21, 22, 23, 25, 26, 27, 28, 29, 30],
        TBL_EC_COMPLETE_PLANS_IDS: [31, 32],
        TBL_MP_JOIN_USER_PLAN_IDS: [66],
        TBL_MP_COMPLETE_BLOCK_IDS: [67],
        TBL_MP_COMPLETE_ACTIVITY_IDS: [68],
        TBL_S_USER_LOGIN_IDS: [890],
        TBL_S_USER_LOGIN_APP_DOWNLOAD_IDS: [12748],
        TBL_FT_BIOMETRICS_IDS: [15944, 16066, 16067, 16068, 16069],
        TBL_COVID_USER_ANSWERS_IDS: [9645],
        TBL_ME_FOD_VIDEO_CLICK_IDS: [71],
        TBL_EM_POST_CLICK_IDS: [75],
        TBL_BIR_BIOMETRICS_POINT_IDS: [4414],
        TBL_U_QUICK_LINK_CLICK_IDS: [43],
        TBL_EV_EVENT_COMPLETE_IDS: [21],
        TBL_QZ_QUIZ_COMPLETE_IDS: [36],
        TBL_FT_ACTIVITY_FEEDS_IDS: [7, 9, 11, 15, 16, 17, 18, 23, 24, 26, 27],
        TBL_FT_SLEEP_FEEDS_IDS: [19, 27, 28],
        TBL_FT_HEART_RATE_FEEDS_IDS: [20],
        TBL_FT_BLOOD_PRESSURE_FEEDS_IDS: [20],
        TBL_FT_FOOD_FEEDS_IDS: [6, 8, 10, 151, 19],
    },
    DISPOSABLE_DOMAINS: [
        "10minutemail.com",
        "20minutemail.com",
        "2prong.com",
        "33mail.com",
        "4warding.com",
        "9mail.com",
        "anonbox.net",
        "boun.cr",
        "burnermail.io",
        "byom.de",
        "dispostable.com",
        "dodgeit.com",
        "dropmail.me",
        "emailondeck.com",
        "fakeinbox.com",
        "filzmail.com",
        "getairmail.com",
        "guerrillamail.com",
        "hushmail.com",
        "inboxbear.com",
        "mail-temp.com",
        "mailcatch.com",
        "maildrop.cc",
        "mailinator.com",
        "mailnesia.com",
        "my10minutemail.com",
        "mytemp.email",
        "nada.email",
        "netmails.net",
        "noclickemail.com",
        "nomail.xyz",
        "onetimeemail.net",
        "sharklasers.com",
        "slopsbox.com",
        "spam4.me",
        "spambog.com",
        "spamex.com",
        "spamfree24.com",
        "spamgourmet.com",
        "spamherelots.com",
        "spaml.de",
        "temp-mail.org",
        "tempmail.net",
        "tempomail.fr",
        "throwawaymail.com",
        "trashmail.com",
        "trashmail.de",
        "yopmail.com",
        "zmail.info",
        "gmail.com",
    ],
    INTERNALLINKS : [
        { id: 0, plugin:'', title: 'Dashboard', path: '/dashboard' },
        { id: 2, plugin:'events', title: 'Event', path: '/events' },
        { id: 4, plugin:'trackers', title: 'Tracker tab (Exercise)', path: '/trackers/exercise' },
        { id: 5, plugin:'trackers',  title: 'Tracker tab (Fitbit)', path: '/device-sync' },
        { id: 6, plugin:'hra', title: 'Health Assessment', path: '/my-health/assessment' },
        { id: 7, plugin:'users', title: 'Edit Profile', path: '/Edit_Profile' },
        { id: 8, plugin:'challenge', title: 'Join Challenges', path: '/join-challenges' },
        { id: 9, plugin:'healthcheckup', title: 'Activities Page', path: '/activities' },
        { id: 10, plugin:'quiz', title: 'Quiz', path: '/quizzes' },
        { id: 12, plugin:'challenge', title: 'My challenge', path: '/my-challenges' },
        { id: 13, plugin:'media', title: 'Fitness videos', path: '/fitness-videos/dashboard' },
        { id: 14, plugin:'healthcheckup', title: 'Health Forms', path: '/Health_Forms' },
        { id: 15, plugin:'activitytracker', title: 'Activity Forms', path: '/Activity_Forms' },
        { id: 16, plugin:'companies', title: 'Support', path: '/support' },
        { id: 17, plugin:'healthcheckup', title: 'My Health tab (Results)', path: '/my-health/results' },
        { id: 18, plugin:'trackers', title: 'Tracker tab (Biometrics)', path: '/trackers/biometrics' },
        { id: 19, plugin:'healthcheckup', title: 'My Health tab (Healthy data)', path: '/my-health/health-data' },
        { id: 20, plugin:'trackers', title: 'Tracker tab (Measurements)', path: '/trackers/measurements' },
        { id: 21, plugin:'internalmail', title: 'Internalmail', path: '/internal-mail' },
        { id: 22, plugin:'emotionalwellbeing', title: 'Emotionalwellbeing', path: '/emotional-well-being/dashboard' },
        { id: 23, plugin:'media', title: 'Media Dashboard', path: '/fitness-videos/dashboard' },
        { id: 24, plugin:'quicklink', title: 'Quicklink', path: '/quick-link' },
        { id: 25, plugin:'myplan', title: 'My Plan', path: '/plans' },
        { id: 26, plugin:'healthcheckup', title: 'Physician Form', path: '/Health_Forms' },
        { id: 27, plugin:'healthcheckup', title: 'Dental Visit Form', path: '/Health_Forms' },
        { id: 29, plugin:'healthcheckup', title: 'Tobacco Affidavit', path: '/Health_Forms' },
        { id: 32, plugin:'events', title: 'Event', path: '/events' },
        { id: 33, plugin:'trackers', title: 'Tracker tab (Nutrition)', path: '/trackers/nutrition' },
    ],
    RECIPETYPE : [
        { id: 1, title: 'Breakfast' },
        { id: 2, title: 'Lunch' },
        { id: 3, title: 'Dinner' },
        { id: 4, title: 'Appetizer' },
        { id: 5, title: 'Dessert' },
        { id: 6, title: 'Snack' },
        { id: 7, title: 'Drink' },
        { id: 8, title: 'Other' },
    ],
    DOMAINS : [ 
    'preventioncloud.com',
    'zomohealth.com'
    ],
    DOMAINS_LIST : [
        'https://dev.preventioncloud.com',
        'https://dev.preventioncloud.com/admin',
        'https://demoaws.preventioncloud.com',
        'https://demoaws.preventioncloud.com/admin',
        'https://preventioncloud.com',
        'https://preventioncloud.com/admin',
        'https://dev.zomohealth.com',
        'https://devadmin.zomohealth.com',
        'https://demo.zomohealth.com',
        'https://demoadmin.zomohealth.com',
        'https://app.zomohealth.com',
        'https://admin.zomohealth.com',
        'https://www.preventioncloud.com',
    ],
    DOMAINS_LIST_ZOMO_HEALTH : [
        'https://dev.zomohealth.com',
        'https://devadmin.zomohealth.com',
        'https://demo.zomohealth.com',
        'https://demoadmin.zomohealth.com',
        'https://app.zomohealth.com',
        'https://admin.zomohealth.com',
    ],
    MAIN : "main",
    READ_REPLICA : "read",
    READ_LOGIN : "login",
    CELLNUMBER : [{ "id": 1, "value": "A"},{ "id": 2, "value": "B"},{ "id": 3, "value": "C"},{ "id": 4, "value": "D"},{ "id": 5, "value": "E"},{ "id": 6, "value": "F"},{ "id": 7, "value": "G"},{ "id": 8, "value": "H"},{ "id": 9, "value": "I"},{ "id": 10, "value": "J"},{ "id": 11, "value": "K"},{ "id": 12, "value": "L"},{ "id": 13, "value": "M"},{ "id": 14, "value": "N"},{ "id": 15, "value": "O"},{ "id": 16, "value": "P"},{ "id": 17, "value": "Q"},{ "id": 18, "value": "R"},{ "id": 19, "value": "S"},{ "id": 20, "value": "T"},{ "id": 21, "value": "U"},{ "id": 22, "value": "V"},{ "id": 23, "value": "W"},{ "id": 24, "value": "X"},{ "id": 25, "value": "Y"},{ "id": 26, "value": "Z"},{ "id": 27, "value": "AA"},{ "id": 28, "value": "AB"},{ "id": 29, "value": "AC"},{ "id": 30, "value": "AD"},{ "id": 31, "value": "AE"},{ "id": 32, "value": "AF"},{ "id": 33, "value": "AG"},{ "id": 34, "value": "AH"},{ "id": 35, "value": "AI"},{ "id": 36, "value": "AJ"},{ "id": 37, "value": "AK"},{ "id": 38, "value": "AL"},{ "id": 39, "value": "AM"},{ "id": 40, "value": "AN"},{ "id": 41, "value": "AO"},{ "id": 42, "value": "AP"},{ "id": 43, "value": "AQ"},{ "id": 44, "value": "AR"},{ "id": 45, "value": "AS"},{ "id": 46, "value": "AT"},{ "id": 47, "value": "AU"},{ "id": 48, "value": "AV"},{ "id": 49, "value": "AW"},{ "id": 50, "value": "AX"},{ "id": 51, "value": "AY"},{ "id": 52, "value": "AZ"},{ "id": 53, "value": "BA"},{ "id": 54, "value": "BB"},{ "id": 55, "value": "BC"},{ "id": 56, "value": "BD"},{ "id": 57, "value": "BE"},{ "id": 58, "value": "BF"},{ "id": 59, "value": "BG"},{ "id": 60, "value": "BH"},{ "id": 61, "value": "BI"},{ "id": 62, "value": "BJ"},{ "id": 63, "value": "BK"},{ "id": 64, "value": "BL"},{ "id": 65, "value": "BM"},{ "id": 66, "value": "BN"},{ "id": 67, "value": "BO"},{ "id": 68, "value": "BP"},{ "id": 69, "value": "BQ"},{ "id": 70, "value": "BR"},{ "id": 71, "value": "BS"},{ "id": 72, "value": "BT"},{ "id": 73, "value": "BU"},{ "id": 74, "value": "BV"},{ "id": 75, "value": "BW"},{ "id": 76, "value": "BX"},{ "id": 77, "value": "BY"},{ "id": 78, "value": "BZ"},{ "id": 79, "value": "CA"},{ "id": 80, "value": "CB"},{ "id": 81, "value": "CC"},{ "id": 82, "value": "CD"},{ "id": 83, "value": "CE"},{ "id": 84, "value": "CF"},{ "id": 85, "value": "CG"},{ "id": 86, "value": "CH"},{ "id": 87, "value": "CI"},{ "id": 88, "value": "CJ"},{ "id": 89, "value": "CK"},{ "id": 90, "value": "CL"},{ "id": 91, "value": "CM"},{ "id": 92, "value": "CN"},{ "id": 93, "value": "CO"},{ "id": 94, "value": "CP"},{ "id": 95, "value": "CQ"},{ "id": 96, "value": "CR"},{ "id": 97, "value": "CS"},{ "id": 98, "value": "CT"},{ "id": 99, "value": "CU"},{ "id": 100, "value": "CV"},{ "id": 101, "value": "CW"},{ "id": 102, "value": "CX"},{ "id": 103, "value": "CY"},{ "id": 104, "value": "CZ"},{ "id": 105, "value": "DA"},{ "id": 106, "value": "DB"},{ "id": 107, "value": "DC"},{ "id": 108, "value": "DD"},{ "id": 109, "value": "DE"},{ "id": 110, "value": "DF"},{ "id": 111, "value": "DG"},{ "id": 112, "value": "DH"},{ "id": 113, "value": "DI"},{ "id": 114, "value": "DJ"},{ "id": 115, "value": "DK"},{ "id": 116, "value": "DL"},{ "id": 117, "value": "DM"},{ "id": 118, "value": "DN"},{ "id": 119, "value": "DO"},{ "id": 120, "value": "DP"},{ "id": 121, "value": "DQ"},{ "id": 122, "value": "DR"},{ "id": 123, "value": "DS"},{ "id": 124, "value": "DT"},{ "id": 125, "value": "DU"},{ "id": 126, "value": "DV"},{ "id": 127, "value": "DW"},{ "id": 128, "value": "DX"},{ "id": 129, "value": "DY"},{ "id": 130, "value": "DZ"},{ "id": 131, "value": "EA"},{ "id": 132, "value": "EB"},{ "id": 133, "value": "EC"},{ "id": 134, "value": "ED"},{ "id": 135, "value": "EE"},{ "id": 136, "value": "EF"},{ "id": 137, "value": "EG"},{ "id": 138, "value": "EH"},{ "id": 139, "value": "EI"},{ "id": 140, "value": "EJ"},{ "id": 141, "value": "EK"},{ "id": 142, "value": "EL"},{ "id": 143, "value": "EM"},{ "id": 144, "value": "EN"},{ "id": 145, "value": "EO"},{ "id": 146, "value": "EP"},{ "id": 147, "value": "EQ"},{ "id": 148, "value": "ER"},{ "id": 149, "value": "ES"},{ "id": 150, "value": "ET"},{ "id": 151, "value": "EU"},{ "id": 152, "value": "EV"},{ "id": 153, "value": "EW"},{ "id": 154, "value": "EX"},{ "id": 155, "value": "EY"},{ "id": 156, "value": "EZ"},{ "id": 157, "value": "FA"},{ "id": 158, "value": "FB"},{ "id": 159, "value": "FC"},{ "id": 160, "value": "FD"},{ "id": 161, "value": "FE"},{ "id": 162, "value": "FF"},{ "id": 163, "value": "FG"},{ "id": 164, "value": "FH"},{ "id": 165, "value": "FI"},{ "id": 166, "value": "FJ"},{ "id": 167, "value": "FK"},{ "id": 168, "value": "FL"},{ "id": 169, "value": "FM"},{ "id": 170, "value": "FN"},{ "id": 171, "value": "FO"},{ "id": 172, "value": "FP"},{ "id": 173, "value": "FQ"},{ "id": 174, "value": "FR"},{ "id": 175, "value": "FS"},{ "id": 176, "value": "FT"},{ "id": 177, "value": "FU"},{ "id": 178, "value": "FV"},{ "id": 179, "value": "FW"},{ "id": 180, "value": "FX"},{ "id": 181, "value": "FY"},{ "id": 182, "value": "FZ"},{ "id": 183, "value": "GA"},{ "id": 184, "value": "GB"},{ "id": 185, "value": "GC"},{ "id": 186, "value": "GD"},{ "id": 187, "value": "GE"},{ "id": 188, "value": "GF"},{ "id": 189, "value": "GG"},{ "id": 190, "value": "GH"},{ "id": 191, "value": "GI"},{ "id": 192, "value": "GJ"},{ "id": 193, "value": "GK"},{ "id": 194, "value": "GL"},{ "id": 195, "value": "GM"},{ "id": 196, "value": "GN"},{ "id": 197, "value": "GO"},{ "id": 198, "value": "GP"},{ "id": 199, "value": "GQ"},{ "id": 200, "value": "GR"},{ "id": 201, "value": "GS"},{ "id": 202, "value": "GT"},{ "id": 203, "value": "GU"},{ "id": 204, "value": "GV"},{ "id": 205, "value": "GW"},{ "id": 206, "value": "GX"},{ "id": 207, "value": "GY"},{ "id": 208, "value": "GZ"},{ "id": 209, "value": "HA"},{ "id": 210, "value": "HB"},{ "id": 211, "value": "HC"},{ "id": 212, "value": "HD"},{ "id": 213, "value": "HE"},{ "id": 214, "value": "HF"},{ "id": 215, "value": "HG"},{ "id": 216, "value": "HH"},{ "id": 217, "value": "HI"},{ "id": 218, "value": "HJ"},{ "id": 219, "value": "HK"},{ "id": 220, "value": "HL"},{ "id": 221, "value": "HM"},{ "id": 222, "value": "HN"},{ "id": 223, "value": "HO"},{ "id": 224, "value": "HP"},{ "id": 225, "value": "HQ"},{ "id": 226, "value": "HR"},{ "id": 227, "value": "HS"},{ "id": 228, "value": "HT"},{ "id": 229, "value": "HU"},{ "id": 230, "value": "HV"},{ "id": 231, "value": "HW"},{ "id": 232, "value": "HX"},{ "id": 233, "value": "HY"},{ "id": 234, "value": "HZ"},{ "id": 235, "value": "IA"},{ "id": 236, "value": "IB"},{ "id": 237, "value": "IC"},{ "id": 238, "value": "ID"},{ "id": 239, "value": "IE"},{ "id": 240, "value": "IF"},{ "id": 241, "value": "IG"},{ "id": 242, "value": "IH"},{ "id": 243, "value": "II"},{ "id": 244, "value": "IJ"},{ "id": 245, "value": "IK"},{ "id": 246, "value": "IL"},{ "id": 247, "value": "IM"},{ "id": 248, "value": "IN"},{ "id": 249, "value": "IO"},{ "id": 250, "value": "IP"},{ "id": 251, "value": "IQ"},{ "id": 252, "value": "IR"},{ "id": 253, "value": "IS"},{ "id": 254, "value": "IT"},{ "id": 255, "value": "IU"},{ "id": 256, "value": "IV"},{ "id": 257, "value": "IW"},{ "id": 258, "value": "IX"},{ "id": 259, "value": "IY"},{ "id": 260, "value": "IZ"},{ "id": 261, "value": "JA"},{ "id": 262, "value": "JB"},{ "id": 263, "value": "JC"},{ "id": 264, "value": "JD"},{ "id": 265, "value": "JE"},{ "id": 266, "value": "JF"},{ "id": 267, "value": "JG"},{ "id": 268, "value": "JH"},{ "id": 269, "value": "JI"},{ "id": 270, "value": "JJ"},{ "id": 271, "value": "JK"},{ "id": 272, "value": "JL"},{ "id": 273, "value": "JM"},{ "id": 274, "value": "JN"},{ "id": 275, "value": "JO"},{ "id": 276, "value": "JP"},{ "id": 277, "value": "JQ"},{ "id": 278, "value": "JR"},{ "id": 279, "value": "JS"},{ "id": 280, "value": "JT"},{ "id": 281, "value": "JU"},{ "id": 282, "value": "JV"},{ "id": 283, "value": "JW"},{ "id": 284, "value": "JX"},{ "id": 285, "value": "JY"},{ "id": 286, "value": "JZ"},{ "id": 287, "value": "KA"},{ "id": 288, "value": "KB"},{ "id": 289, "value": "KC"},{ "id": 290, "value": "KD"},{ "id": 291, "value": "KE"},{ "id": 292, "value": "KF"},{ "id": 293, "value": "KG"},{ "id": 294, "value": "KH"},{ "id": 295, "value": "KI"},{ "id": 296, "value": "KJ"},{ "id": 297, "value": "KK"},{ "id": 298, "value": "KL"},{ "id": 299, "value": "KM"},{ "id": 300, "value": "KN"},{ "id": 301, "value": "KO"},{ "id": 302, "value": "KP"},{ "id": 303, "value": "KQ"},{ "id": 304, "value": "KR"},{ "id": 305, "value": "KS"},{ "id": 306, "value": "KT"},{ "id": 307, "value": "KU"},{ "id": 308, "value": "KV"},{ "id": 309, "value": "KW"},{ "id": 310, "value": "KX"},{ "id": 311, "value": "KY"},{ "id": 312, "value": "KZ"},{ "id": 313, "value": "LA"},{ "id": 314, "value": "LB"},{ "id": 315, "value": "LC"},{ "id": 316, "value": "LD"},{ "id": 317, "value": "LE"},{ "id": 318, "value": "LF"},{ "id": 319, "value": "LG"},{ "id": 320, "value": "LH"},{ "id": 321, "value": "LI"},{ "id": 322, "value": "LJ"},{ "id": 323, "value": "LK"},{ "id": 324, "value": "LL"},{ "id": 325, "value": "LM"},{ "id": 326, "value": "LN"},{ "id": 327, "value": "LO"},{ "id": 328, "value": "LP"},{ "id": 329, "value": "LQ"},{ "id": 330, "value": "LR"},{ "id": 331, "value": "LS"},{ "id": 332, "value": "LT"},{ "id": 333, "value": "LU"},{ "id": 334, "value": "LV"},{ "id": 335, "value": "LW"},{ "id": 336, "value": "LX"},{ "id": 337, "value": "LY"},{ "id": 338, "value": "LZ"},{ "id": 339, "value": "MA"},{ "id": 340, "value": "MB"},{ "id": 341, "value": "MC"},{ "id": 342, "value": "MD"},{ "id": 343, "value": "ME"},{ "id": 344, "value": "MF"},{ "id": 345, "value": "MG"},{ "id": 346, "value": "MH"},{ "id": 347, "value": "MI"},{ "id": 348, "value": "MJ"},{ "id": 349, "value": "MK"},{ "id": 350, "value": "ML"},{ "id": 351, "value": "MM"},{ "id": 352, "value": "MN"},{ "id": 353, "value": "MO"},{ "id": 354, "value": "MP"},{ "id": 355, "value": "MQ"},{ "id": 356, "value": "MR"},{ "id": 357, "value": "MS"},{ "id": 358, "value": "MT"},{ "id": 359, "value": "MU"},{ "id": 360, "value": "MV"},{ "id": 361, "value": "MW"},{ "id": 362, "value": "MX"},{ "id": 363, "value": "MY"},{ "id": 364, "value": "MZ"},{ "id": 365, "value": "NA"},{ "id": 366, "value": "NB"},{ "id": 367, "value": "NC"},{ "id": 368, "value": "ND"},{ "id": 369, "value": "NE"},{ "id": 370, "value": "NF"},{ "id": 371, "value": "NG"},{ "id": 372, "value": "NH"},{ "id": 373, "value": "NI"},{ "id": 374, "value": "NJ"},{ "id": 375, "value": "NK"},{ "id": 376, "value": "NL"},{ "id": 377, "value": "NM"},{ "id": 378, "value": "NN"},{ "id": 379, "value": "NO"},{ "id": 380, "value": "NP"},{ "id": 381, "value": "NQ"},{ "id": 382, "value": "NR"},{ "id": 383, "value": "NS"},{ "id": 384, "value": "NT"},{ "id": 385, "value": "NU"},{ "id": 386, "value": "NV"},{ "id": 387, "value": "NW"},{ "id": 388, "value": "NX"},{ "id": 389, "value": "NY"},{ "id": 390, "value": "NZ"},{ "id": 391, "value": "OA"},{ "id": 392, "value": "OB"},{ "id": 393, "value": "OC"},{ "id": 394, "value": "OD"},{ "id": 395, "value": "OE"},{ "id": 396, "value": "OF"},{ "id": 397, "value": "OG"},{ "id": 398, "value": "OH"},{ "id": 399, "value": "OI"},{ "id": 400, "value": "OJ"},{ "id": 401, "value": "OK"},{ "id": 402, "value": "OL"},{ "id": 403, "value": "OM"},{ "id": 404, "value": "ON"},{ "id": 405, "value": "OO"},{ "id": 406, "value": "OP"},{ "id": 407, "value": "OQ"},{ "id": 408, "value": "OR"},{ "id": 409, "value": "OS"},{ "id": 410, "value": "OT"},{ "id": 411, "value": "OU"},{ "id": 412, "value": "OV"},{ "id": 413, "value": "OW"},{ "id": 414, "value": "OX"},{ "id": 415, "value": "OY"},{ "id": 416, "value": "OZ"},{ "id": 417, "value": "PA"},{ "id": 418, "value": "PB"},{ "id": 419, "value": "PC"},{ "id": 420, "value": "PD"},{ "id": 421, "value": "PE"},{ "id": 422, "value": "PF"},{ "id": 423, "value": "PG"},{ "id": 424, "value": "PH"},{ "id": 425, "value": "PI"},{ "id": 426, "value": "PJ"},{ "id": 427, "value": "PK"},{ "id": 428, "value": "PL"},{ "id": 429, "value": "PM"},{ "id": 430, "value": "PN"},{ "id": 431, "value": "PO"},{ "id": 432, "value": "PP"},{ "id": 433, "value": "PQ"},{ "id": 434, "value": "PR"},{ "id": 435, "value": "PS"},{ "id": 436, "value": "PT"},{ "id": 437, "value": "PU"},{ "id": 438, "value": "PV"},{ "id": 439, "value": "PW"},{ "id": 440, "value": "PX"},{ "id": 441, "value": "PY"},{ "id": 442, "value": "PZ"},{ "id": 443, "value": "QA"},{ "id": 444, "value": "QB"},{ "id": 445, "value": "QC"},{ "id": 446, "value": "QD"},{ "id": 447, "value": "QE"},{ "id": 448, "value": "QF"},{ "id": 449, "value": "QG"},{ "id": 450, "value": "QH"},{ "id": 451, "value": "QI"},{ "id": 452, "value": "QJ"},{ "id": 453, "value": "QK"},{ "id": 454, "value": "QL"},{ "id": 455, "value": "QM"},{ "id": 456, "value": "QN"},{ "id": 457, "value": "QO"},{ "id": 458, "value": "QP"},{ "id": 459, "value": "QQ"},{ "id": 460, "value": "QR"},{ "id": 461, "value": "QS"},{ "id": 462, "value": "QT"},{ "id": 463, "value": "QU"},{ "id": 464, "value": "QV"},{ "id": 465, "value": "QW"},{ "id": 466, "value": "QX"},{ "id": 467, "value": "QY"},{ "id": 468, "value": "QZ"},{ "id": 469, "value": "RA"},{ "id": 470, "value": "RB"},{ "id": 471, "value": "RC"},{ "id": 472, "value": "RD"},{ "id": 473, "value": "RE"},{ "id": 474, "value": "RF"},{ "id": 475, "value": "RG"},{ "id": 476, "value": "RH"},{ "id": 477, "value": "RI"},{ "id": 478, "value": "RJ"},{ "id": 479, "value": "RK"},{ "id": 480, "value": "RL"},{ "id": 481, "value": "RM"},{ "id": 482, "value": "RN"},{ "id": 483, "value": "RO"},{ "id": 484, "value": "RP"},{ "id": 485, "value": "RQ"},{ "id": 486, "value": "RR"},{ "id": 487, "value": "RS"},{ "id": 488, "value": "RT"},{ "id": 489, "value": "RU"},{ "id": 490, "value": "RV"},{ "id": 491, "value": "RW"},{ "id": 492, "value": "RX"},{ "id": 493, "value": "RY"},{ "id": 494, "value": "RZ"},{ "id": 495, "value": "SA"},{ "id": 496, "value": "SB"},{ "id": 497, "value": "SC"},{ "id": 498, "value": "SD"},{ "id": 499, "value": "SE"},{ "id": 500, "value": "SF"},{ "id": 501, "value": "SG"},{ "id": 502, "value": "SH"},{ "id": 503, "value": "SI"},{ "id": 504, "value": "SJ"},{ "id": 505, "value": "SK"},{ "id": 506, "value": "SL"},{ "id": 507, "value": "SM"},{ "id": 508, "value": "SN"},{ "id": 509, "value": "SO"},{ "id": 510, "value": "SP"},{ "id": 511, "value": "SQ"},{ "id": 512, "value": "SR"},{ "id": 513, "value": "SS"},{ "id": 514, "value": "ST"},{ "id": 515, "value": "SU"},{ "id": 516, "value": "SV"},{ "id": 517, "value": "SW"},{ "id": 518, "value": "SX"},{ "id": 519, "value": "SY"},{ "id": 520, "value": "SZ"},{ "id": 521, "value": "TA"},{ "id": 522, "value": "TB"},{ "id": 523, "value": "TC"},{ "id": 524, "value": "TD"},{ "id": 525, "value": "TE"},{ "id": 526, "value": "TF"},{ "id": 527, "value": "TG"},{ "id": 528, "value": "TH"},{ "id": 529, "value": "TI"},{ "id": 530, "value": "TJ"},{ "id": 531, "value": "TK"},{ "id": 532, "value": "TL"},{ "id": 533, "value": "TM"},{ "id": 534, "value": "TN"},{ "id": 535, "value": "TO"},{ "id": 536, "value": "TP"},{ "id": 537, "value": "TQ"},{ "id": 538, "value": "TR"},{ "id": 539, "value": "TS"},{ "id": 540, "value": "TT"},{ "id": 541, "value": "TU"},{ "id": 542, "value": "TV"},{ "id": 543, "value": "TW"},{ "id": 544, "value": "TX"},{ "id": 545, "value": "TY"},{ "id": 546, "value": "TZ"},{ "id": 547, "value": "UA"},{ "id": 548, "value": "UB"},{ "id": 549, "value": "UC"},{ "id": 550, "value": "UD"},{ "id": 551, "value": "UE"},{ "id": 552, "value": "UF"},{ "id": 553, "value": "UG"},{ "id": 554, "value": "UH"},{ "id": 555, "value": "UI"},{ "id": 556, "value": "UJ"},{ "id": 557, "value": "UK"},{ "id": 558, "value": "UL"},{ "id": 559, "value": "UM"},{ "id": 560, "value": "UN"},{ "id": 561, "value": "UO"},{ "id": 562, "value": "UP"},{ "id": 563, "value": "UQ"},{ "id": 564, "value": "UR"},{ "id": 565, "value": "US"},{ "id": 566, "value": "UT"},{ "id": 567, "value": "UU"},{ "id": 568, "value": "UV"},{ "id": 569, "value": "UW"},{ "id": 570, "value": "UX"},{ "id": 571, "value": "UY"},{ "id": 572, "value": "UZ"},{ "id": 573, "value": "VA"},{ "id": 574, "value": "VB"},{ "id": 575, "value": "VC"},{ "id": 576, "value": "VD"},{ "id": 577, "value": "VE"},{ "id": 578, "value": "VF"},{ "id": 579, "value": "VG"},{ "id": 580, "value": "VH"},{ "id": 581, "value": "VI"},{ "id": 582, "value": "VJ"},{ "id": 583, "value": "VK"},{ "id": 584, "value": "VL"},{ "id": 585, "value": "VM"},{ "id": 586, "value": "VN"},{ "id": 587, "value": "VO"},{ "id": 588, "value": "VP"},{ "id": 589, "value": "VQ"},{ "id": 590, "value": "VR"},{ "id": 591, "value": "VS"},{ "id": 592, "value": "VT"},{ "id": 593, "value": "VU"},{ "id": 594, "value": "VV"},{ "id": 595, "value": "VW"},{ "id": 596, "value": "VX"},{ "id": 597, "value": "VY"},{ "id": 598, "value": "VZ"},{ "id": 599, "value": "WA"},{ "id": 600, "value": "WB"},{ "id": 601, "value": "WC"},{ "id": 602, "value": "WD"},{ "id": 603, "value": "WE"},{ "id": 604, "value": "WF"},{ "id": 605, "value": "WG"},{ "id": 606, "value": "WH"},{ "id": 607, "value": "WI"},{ "id": 608, "value": "WJ"},{ "id": 609, "value": "WK"},{ "id": 610, "value": "WL"},{ "id": 611, "value": "WM"},{ "id": 612, "value": "WN"},{ "id": 613, "value": "WO"},{ "id": 614, "value": "WP"},{ "id": 615, "value": "WQ"},{ "id": 616, "value": "WR"},{ "id": 617, "value": "WS"},{ "id": 618, "value": "WT"},{ "id": 619, "value": "WU"},{ "id": 620, "value": "WV"},{ "id": 621, "value": "WW"},{ "id": 622, "value": "WX"},{ "id": 623, "value": "WY"},{ "id": 624, "value": "WZ"},{ "id": 625, "value": "XA"},{ "id": 626, "value": "XB"},{ "id": 627, "value": "XC"},{ "id": 628, "value": "XD"},{ "id": 629, "value": "XE"},{ "id": 630, "value": "XF"},{ "id": 631, "value": "XG"},{ "id": 632, "value": "XH"},{ "id": 633, "value": "XI"},{ "id": 634, "value": "XJ"},{ "id": 635, "value": "XK"},{ "id": 636, "value": "XL"},{ "id": 637, "value": "XM"},{ "id": 638, "value": "XN"},{ "id": 639, "value": "XO"},{ "id": 640, "value": "XP"},{ "id": 641, "value": "XQ"},{ "id": 642, "value": "XR"},{ "id": 643, "value": "XS"},{ "id": 644, "value": "XT"},{ "id": 645, "value": "XU"},{ "id": 646, "value": "XV"},{ "id": 647, "value": "XW"},{ "id": 648, "value": "XX"},{ "id": 649, "value": "XY"},{ "id": 650, "value": "XZ"},{ "id": 651, "value": "YA"},{ "id": 652, "value": "YB"},{ "id": 653, "value": "YC"},{ "id": 654, "value": "YD"},{ "id": 655, "value": "YE"},{ "id": 656, "value": "YF"},{ "id": 657, "value": "YG"},{ "id": 658, "value": "YH"},{ "id": 659, "value": "YI"},{ "id": 660, "value": "YJ"},{ "id": 661, "value": "YK"},{ "id": 662, "value": "YL"},{ "id": 663, "value": "YM"},{ "id": 664, "value": "YN"},{ "id": 665, "value": "YO"},{ "id": 666, "value": "YP"},{ "id": 667, "value": "YQ"},{ "id": 668, "value": "YR"},{ "id": 669, "value": "YS"},{ "id": 670, "value": "YT"},{ "id": 671, "value": "YU"},{ "id": 672, "value": "YV"},{ "id": 673, "value": "YW"},{ "id": 674, "value": "YX"},{ "id": 675, "value": "YY"},{ "id": 676, "value": "YZ"},{ "id": 677, "value": "ZA"},{ "id": 678, "value": "ZB"},{ "id": 679, "value": "ZC"},{ "id": 680, "value": "ZD"},{ "id": 681, "value": "ZE"},{ "id": 682, "value": "ZF"},{ "id": 683, "value": "ZG"},{ "id": 684, "value": "ZH"},{ "id": 685, "value": "ZI"},{ "id": 686, "value": "ZJ"},{ "id": 687, "value": "ZK"},{ "id": 688, "value": "ZL"},{ "id": 689, "value": "ZM"},{ "id": 690, "value": "ZN"},{ "id": 691, "value": "ZO"},{ "id": 692, "value": "ZP"},{ "id": 693, "value": "ZQ"},{ "id": 694, "value": "ZR"},{ "id": 695, "value": "ZS"},{ "id": 696, "value": "ZT"},{ "id": 697, "value": "ZU"},{ "id": 698, "value": "ZV"},{ "id": 699, "value": "ZW"},{ "id": 700, "value": "ZX"},{ "id": 701, "value": "ZY"},{ "id": 702, "value": "ZZ" }],
    BROKER_LIST : [ 
        { "id": 1, "name": "USI" },
        { "id": 2, "name": "Allian" },
        { "id": 3, "name": "CBIZ" },
        { "id": 4, "name": "Gallagher" },
        { "id": 5, "name": "Risk Strategies" },
        { "id": 6, "name": "Brown" },
        { "id": 7, "name": "Assurance" },
        { "id": 8, "name": "HUB" },
        { "id": 9, "name": "Willis Towers Watson Insurance Services West, Inc" },
        { "id": 10, "name": "Aon" },
        { "id": 11, "name": "MMA" },
        { "id": 12, "name": "Hylant" },
        { "id": 13, "name": "Gibson" },
        { "id": 14, "name": "The Horton Group" },
        { "id": 15, "name": "NFP" },
        { "id": 16, "name": "The Baldwin Group" },
        { "id": 17, "name": "Mark III" },
        { "id": 18, "name": "Other" },
    ],
    ORG_INDUSTRY_LIST : [
    { "id": 1, "name": "Advertising" },
    { "id": 2, "name": "Marketing" },
    { "id": 3, "name": "Finance" },
    { "id": 4, "name": "Insurance" },
    { "id": 5, "name": "Manufacturing" },
    { "id": 6, "name": "Healthcare" },
    { "id": 7, "name": "Agriculture" },
    { "id": 8, "name": "Arts and Entertainment" },
    { "id": 9, "name": "Construction" },
    { "id": 10, "name": "Education" },
    { "id": 11, "name": "Forestry" },
    { "id": 12, "name": "Mining" },
    { "id": 13, "name": "Sales" },
    { "id": 14, "name": "Transportation" },
    { "id": 15, "name": "Hospitality" },
    { "id": 16, "name": "Technology" },
    { "id": 17, "name": "Energy" },
    { "id": 18, "name": "Engineering" },
    { "id": 19, "name": "Information" },
    { "id": 20, "name": "Community and Social Services" },
    { "id": 21, "name": "Government" },
    { "id": 22, "name": "Staffing" },
    { "id": 23, "name": "Telecomms" },
    { "id": 24, "name": "Communications" },
    { "id": 25, "name": "Animal Sciences" },
    { "id": 26, "name": "Pharmacy" },
    { "id": 27, "name": "Fitness" },
    { "id": 28, "name": "Recreation" },
    { "id": 29, "name": "Other" }
    ],
    REPORT_LIST : {
                1: "Incentive",
                2: "My Plan",
                3: "Challenge",
                4: "COVID19",
                5: "Quicklink",
                6: "Fitness Video",
                7: "Billboards",
                8: "Event",
                9: "Health",
                10: "Activity",
                11: "Quiz",
                12: "Emotional Well-Being",
                13: "Survey",
                14: "Engagement Comparison",
                15: "Reimbursements",
                16: "Biometrics",
            },
    USER_ALL_POPUP : {
                    "loginaggrement": 0,
                    "covidPassport": 1,
                    "covidVaccinePopup": 2,
                    "agreement": 3,
                    "event_remider_popup": 4,
                    "Questionnaireuser": 5,
                    "information_popup": 6,
                    "health_popup": 7,
                    "activity_popup": 8,
                    "reimbursement_form": 9,
                    "TokenReceivedPopup": 10,
                    "UserServeyPopupShow": 11,
                    "loginpointsleaderboardpopup": 12, 
                    "challengeRelayRace": 13,
                    "challengeMoveMore": 14,
                },
    WEEKDAYS: {
                'sunday': 0,
                'monday': 1,
                'tuesday': 2,
                'wednesday': 3,
                'thursday': 4,
                'friday': 5,
                'saturday': 6
            },
    table_HEADER_DATA: {'A': 'department_id','B': 'status','C': 'relationship_code','D': 'relationship_id','E': 'role_id','F': 'id_of_direct_supervisor','G': 'username','H': 'first_name','I': 'middle_name','J': 'last_name','K': 'jobtitle','L': 'securitycode','M': 'employeeid','N': 'gender','O': 'dob','P': 'date_of_hire','Q': 'on_insurance_plan','R': 'insurance_plan_name','S': 'email','T': 'wphone','U': 'wphone_ext','V': 'location','W': 'work_address_1','X': 'work_address_2','Y': 'work_city','Z': 'work_state','AA': 'work_zip','AB': 'work_country','AC': 'hphone','AD': 'cphone','AE': 'address','AF': 'address_2','AG': 'city','AH': 'state','AI': 'zip','AJ': 'country','AK': 'code','AL': 'is_camp_eligible','AM': 'email_receiving','AN': 'email_update'},
    table_SPOUSE_HEADER_DATA: { 'BA': 'spouse_first_name', 'BB': 'spouse_last_name', 'BC': 'spouse_dob', 'BD': 'spouse_gender', 'BE': 'spouse_email', 'BF': 'spouse_on_health_plan', 'BG': 'spouse_health_plan_name' },
    table_LINKED_HEADER_DATA: { 'CA': 'linked_emp_id' },
      TABLES: {
        s_users: 'users',
        s_users_settings: 'users',
        s_roles: 'users',
        s_spouse: 'users',
        s_tabsettings: 'users',
        s_import_user_request: 'user_other',
        s_user_login_agreenment: 'user_other',
        c_companies: 'company',
        c_company_contract: 'company',
        c_company_meta: 'company',
        c_company_settings: 'company',
        c_company_cem_info: 'company_other',
        c_companytypes: 'company',
        c_activeplugins: 'company',
        c_keycontacts: 'company_other',
        c_assignbrokers: 'company_other',
        c_physiciantemps: 'company_other',
        c_spouseagreements: 'company_other',
        c_wellnessassignments: 'company_other',
        c_assign_engmanagers: 'company_other',
        c_masscommunications: 'company_other',
        c_global_access: 'company_other',
        c_internallinks: 'c_internallinks',
        c_companydashboards: 'c_companydashboards',
        c_reportmenusettings: 'c_reportmenusettings',
        c_sidemenusettings: 'c_sidemenusettings',
        c_supports: 'c_supports',
        c_census_custom_fields: 'census',
        c_census_custom_fields_values: 'census',
        c_census_frequency: 'census',
        c_surveyanswers: 'survey',
        c_surveypopup: 'survey',
        c_surveyquestions: 'survey',
        c_surveyuseranswers: 'survey',
        co_coaches: 'coach',
        co_notes: 'coach',
        c_covidanswers: 'covid',
        c_covidquestions: 'covid',
        c_covidsettings: 'covid',
        c_coviduseranswers: 'covid',
        c_covid_passport_user: 'covid',
        c_covidpassportsettings: 'covid',
        c_covidvaccinationtype: 'covid',
        c_departments: 'company_department_location',
        c_locations: 'company_department_location',
        c_client_manager_assignment: 'company_client_manager_assign',
        c_membership_plan: 'company_other',
        ev_departments: 'event_department_location',
        ev_locations: 'event_department_location',
        s_languages: 'language',
        lg_company_languages: 'language',
        s_permission_methods: 'permission',
        s_permission_roles: 'permission',
        in_activity: 'activity',
        in_category: 'activity',
        tm_themes_core: 'theme',
        tm_setting: 'theme',
        tm_dashboard_widgets: 'theme',
        tm_theme_setting: 'theme',
        at_create_forms: 'activity_tracker',
        at_submited_forms: 'activity_tracker',
        re_create_forms: 'reimbursement',
        re_submited_forms: 'reimbursement',
        hc_datamanagers: 'health_checkup',
        hc_downloadforms: 'health_checkup',
        hc_questionnairesettings: 'health_checkup',
        hc_questionnaireusers: 'health_checkup',
        hc_zipdownloads: 'health_checkup',
        hc_forminstructions: 'hc_forminstructions',
        hc_userformsattachments: 'health_checkup_userforms',
        hc_userforms: 'health_checkup_userforms',
        hc_authorizations: 'hc_tabaccouses',
        hc_tabaccouses: 'hc_tabaccouses',
        hc_dentists: 'hc_tabaccouses',
        hc_optometrists: 'hc_tabaccouses',
        hc_biometric_health_request: 'hc_tabaccouses',
        bir_biometric_org_setting: 'biometrics_other',
        bir_org_biometric: 'biometrics_other',
        bir_biometric: 'biometrics_other',
        br_brokers: 'broker',
        br_region_state_city: 'broker',
        br_regions: 'broker',
        u_quicklink: 'u_quicklink',
        u_quicklink_clicks: 'quicklink_other',
        u_quicklink_folders: 'quicklink_other',
        u_quicklink_folder_orglists: 'quicklink_other',
        u_quicklink_orglists: 'quicklink_other',
        u_quicklink_report: 'quicklink_other',
        ev_event_category: 'event',
        ev_events: 'event',
        ev_global_events: 'event',
        ev_externallink_user: 'event_other',
        ev_organization: 'event_other',
        ev_reminders: 'event_other',
        re_event_reports: 'event_other',
        ev_slots: 'event_slot',
        ev_slotstimings: 'event_slot',
        ev_userbookinglists: 'ev_userbookinglists',
        qz_quizzes: 'quiz',
        qz_categories: 'quiz',
        qz_quiz_clicks: 'quiz_details',
        qz_quiz_details: 'quiz_details',
        qz_quiz_orgs: 'quiz_details',
        qz_quiz_sections: 'quiz_details',
        qz_truefalse_questions: 'quiz_details',
        qz_fillup_questions: 'quiz_other',
        qz_hotspot_questions: 'quiz_other',
        qz_matchingdragdrop_questions: 'quiz_other',
        qz_matchingdropdown_questions: 'quiz_other',
        qz_multiplechoice_questions: 'quiz_other',
        qz_multipleresponse_questions: 'quiz_other',
        qz_multiple_questions: 'quiz_other',
        qz_assign_quiz_orgs: 'qz_assign_quiz_orgs',
        qz_quiz_user_details: 'quiz_user',
        qz_user_details: 'quiz_user',
        mp_assign_user_plan: 'mp_assign_user_plan',
        mp_join_user_plan: 'mp_join_user_plan',
        mp_plans: 'my_plan',
        mp_activity: 'my_plan',
        mp_blocks: 'my_plan',
        mp_bussiness_rule: 'my_plan',
        mp_description: 'my_plan',
        mp_assign_activity: 'my_plan_other',
        mp_assign_block: 'my_plan_other',
        mp_assign_plan: 'my_plan_other',
        mp_assign_rule: 'my_plan_other',
        mp_complete_activity: 'my_plan_complete',
        mp_complete_block: 'my_plan_complete',
        uca_setting: 'upcomming_activities',
        uca_manual_upcomings: 'upcomming_activities',
        cl_reports: 'claim',
        cl_codes: 'claim',
        dmt_files_organizations: 'data_management',
        dmt_files: 'data_management',
        dmt_document: 'data_management',
        dmimporthistories: 'data_management',
        dmimporthistorycolumns: 'data_management',
        ds_diseases: 'disease_management',
        ds_forms: 'disease_management',
        ds_forms_coverpages: 'disease_management',
        ds_manage_diseases: 'disease_management',
        ds_manage_forms: 'disease_management',
        ds_physician_forms: 'disease_management',
        ds_standard_cares: 'disease_management',
        em_tag: 'emotional_wellbeing',
        em_tag_assign: 'emotional_wellbeing',
        em_post_click: 'emotional_wellbeing',
        em_category: 'emotional_wellbeing_post',
        em_post: 'emotional_wellbeing_post',
        me_category: 'media_fitness_post',
        me_post: 'media_fitness_post',
        me_fod_category: 'media_fitness_other',
        me_fod_difficulty: 'media_fitness_other',
        me_fod_durationrange: 'media_fitness_other',
        me_fod_equipment: 'media_fitness_other',
        me_fod_focus: 'media_fitness_other',
        me_fod_instructors: 'media_fitness_other',
        me_fod_instructors_status: 'media_fitness_other',
        me_fod_series: 'media_fitness_other',
        me_fod_video_categories: 'media_fitness_video',
        me_fod_video_click: 'media_fitness_video',
        me_fod_video_equipments: 'media_fitness_video',
        me_fod_video_focus: 'media_fitness_video',
        me_fod_video_instructors: 'media_fitness_video',
        me_fod_video_series: 'media_fitness_video',
        me_fod_video_status: 'media_fitness_video',
        me_fod_videos: 'me_fod_videos',
        in_other_reward: 'in_other_reward',
        in_campaign_reward: 'in_campaign_reward',
        in_cash_reward: 'in_cash_reward',
        in_campaign: 'in_campaign',
        in_campaign_activity: 'in_campaign_activity',
        in_campaign_category: 'in_campaign_category',
        in_campaign_challenge: 'in_campaign_challenge',
        in_insurance_plan: 'incentive',
        in_incentive_reports: 'incentive',
        in_insurance_reward: 'incentive',
        in_custom_point: 'in_custom_point',
        in_slider_settings: 'incentive_setting',
        in_spouse_settings: 'incentive_setting',
        ha_assessment_texts: 'health_assessment_other',
        ha_reportdownloads: 'health_assessment_other',
        ha_cohortreports: 'health_assessment_other',
        ha_assessment_results: 'health_assessment_results',
        ha_assessment_settings: 'health_assessment_results',
        ha_assessment_tabs: 'health_assessment_results',
        ha_assessment_options: 'health_assessment_details',
        ha_assessment_options_details: 'health_assessment_details',
        ha_assessment_questions: 'health_assessment_details',
        ha_assessment_questions_details: 'health_assessment_details',
        ha_assessments: 'ha_assessments',
        ha_options: 'health_assessment',
        ha_questions: 'health_assessment',
        ha_emotional_assessments: 'ha_emotional_assessments',
        ha_emotional_assessments_answer: 'ha_emotional_assessments_answer',
        ha_emotional_assessments_result: 'ha_emotional_assessments_result',
        dc_authorized_users: 'device_configuration',
        dc_configurations: 'device_configuration',
        com_email: 'communication',
        com_email_attachments: 'communication',
        com_email_attachmenttypes: 'communication',
        com_email_to: 'communication',
        com_templatetexts: 'communication',
        ft_foods_feeds: 'ft_foods_feeds',
        ft_body_feeds: 'ft_body_feeds',
        ft_food_nutrition_values: 'ft_food_nutrition_values',
        ft_authorizedusers: 'ft_authorizedusers',
        ft_activity_feeds: 'ft_activity_feeds',
        hc_biometrics: 'biometrics',
        ha_hrabiometrics: 'biometrics',
        ft_biomatrics: 'biometrics',
        ch_ac_olympic_data: 'challenge_other',
        ch_bingo_week_labels: 'challenge_other',
        ch_step_checkpoints: 'challenge_other',
        ch_tokens: 'challenge_other',
        ch_bio_weight: 'challenge_other',
        ch_commitment_levels: 'challenge_other',
        ch_fitness_activity: 'challenge_other',
        ch_move_more_parks: 'challenge_other',
        ch_recipe: 'challenge_other',
        ch_chat: 'challenge_chat',
        ch_chat_settings: 'challenge_chat',
        ch_banned_word: 'challenge_chat',
        ch_fitness_users_activity: 'fitness_users_activity',
        ch_square_users: 'fitness_users_activity',
        ch_schedule_challenge_join_users: 'ch_schedule_challenge_join_users',
        ch_squares: 'challenge_square',
        ch_cards: 'challenge_square',
        ch_challenge: 'challenge',
        ch_challenge_activity: 'challenge',
        ch_schedule_challenge: 'challenge_schedule',
        ch_schedule_challenge_agreement: 'challenge_schedule',
        ch_days: 'challenge_day',
        ch_weeks: 'challenge_day',
        ch_days_users: 'challenge_dayweek_users',
        ch_weeks_users: 'challenge_dayweek_users',
        ch_weeks_steps: 'challenge_week',
        ch_org_weeks: 'challenge_week',
        ch_teams: 'challenge_team',
        ch_groups: 'challenge_team',
        ch_team_members: 'ch_team_members',
        ch_team_schedule: 'ch_team_schedule',
        ch_invite_temp: 'challenge_invite',
        ch_invite_user: 'challenge_invite',
        ch_org_invites: 'challenge_invite',
        ch_health_activity: 'challenge_activity',
        ch_health_request: 'challenge_activity',
        ch_health_users_activity: 'challenge_activity',
        ch_health_week: 'challenge_activity',
        error_log: 'error_log',
        default: 'default',
    },
    LINKED_DEFAULT_HEADER: { 'CA': 'Linked Emp Id'},

    USER_TABLE: [
        'code',
        'role_id',
        'first_name',
        'middle_name',
        'last_name',
        'gender',
        'username',
        'email',
        'p_email',
        'dob',
        'date_of_hire',
        'employeeid',
        'securitycode',
        'timezone',
        'password',
        'new_password',
        'docpassword',
        'ssoIdentifier',
        'profile_image',
        'activation_key',
        'on_insurance_plan',
        'insurance_plan_name',
        'location',
        'department_id',
        'physiciantype_id',
        'pname',
        'companytype_id',
        'org_id',
        'membership_code',
        'entered_code',
        'num_login',
        'last_login',
        'user_type',
        'on_current_census',
        'relationship_id',
        'status',
        'refresh_token',
        'is_camp_eligible',
        'api_key',
        'api_secret',
        'lastuniqid'
    ],
    USER_SETTING_TABLE: [
        'address',
        'address2',
        'city',
        'state',
        'country',
        'zip',
        'wphone',
        'cphone',
        'hphone',
        'fax',
        'wmaddress',
        'jobtitle',
        'wphone_ext',
        'otp_key',
        'otp_created',
        'otp_generated_by',
        'num_otp_login',
        'coach_type',
        'communication_type',
        'coach_area',
        'azure_objectid',
        'autouser',
        'device_token',
        'popup_status',
        'is_aro_build',
        'info_popup_status',
        'videofavoriteslist',
        'fitnessvideofavoriteslist',
        'is_pointsleaderboardpopup',
        'email_update',
        'email_receiving',
        'unsubscribe_reason',
        'receivetokens',
        'linkedin_link',
        'instagram_link',
        'twitter_link',
        'facebook_link'
    ],
    CENSUS_USER_LIST: [
        'user.id',
        'user.status',
        'user.department_id',
        'user.relationship_id',
        'user.role_id',
        'user.username',
        'user.first_name',
        'user.middle_name',
        'user.last_name',
        'settings.jobtitle',
        'user.securitycode',
        'user.employeeid',
        'user.gender',
        'user.dob',
        'user.date_of_hire',
        'user.on_insurance_plan',
        'user.insurance_plan_name',
        'user.email',
        'settings.wphone',
        'settings.wphone_ext',
        'user.location',
        'settings.hphone',
        'settings.cphone',
        'settings.address',
        'settings.address2',
        'settings.city',
        'settings.state',
        'settings.zip',
        'settings.country',
        'user.code',
        'user.timezone',
        'user.is_camp_eligible',
        'settings.email_receiving',
        'settings.email_update',
        'settings.id',
        'settings.user_id',
    ],
    WEIGHT_REQUEST_DATA: ['User ID','Organization ID','Username','First Name','Middle Name','Last Name','Social Security Number','Employee ID','Gender','Birth Date','Email'],
    HEALTH_REQUEST_DATA: ["User ID","Organization ID","First Name","Middle Name","Last Name","Social Security Number","Employee ID","Gender","Birth Date","Email","Physician ID","Physician First Name","Physician Last Name","Physician Email","Office Phone","Height","Weight","BMI","Blood Pressure- Systolic","Blood Pressure- Diastolic","Fasting or Random","Glucose","A1C","Total Cholesterol","HDL Cholesterol","LDL Cholesterol","Triglycerides","Date PF Received","Dentist ID","Dentist First Name","Dentist Last Name","Dentist Email","Office Phone","Date DF Received","Optometrist ID","Optometrist First Name","Optometrist Last Name","Optometrist Email","Office Phone","Date OVF Received","Waist"],
    BIOMETRIC_HEALTH_REQUEST_HEADER_DATA: {A: "User ID", B: "Organization ID", C: "First Name", D: "Middle Name", E: "Last Name", F: "Social Security Number", G: "Employee ID", H: "Gender", I: "Birth Date", J: "Email", K: "Physician ID", L: "Physician First Name", M: "Physician Last Name", N: "Physician Email", O: "Office Phone", P: "Height", Q: "Weight", R: "BMI", S: "Blood Pressure- Systolic", T: "Blood Pressure- Diastolic", U: "Fasting or Random", V: "Glucose", W: "A1C", X: "Total Cholesterol", Y: "HDL Cholesterol", Z: "LDL Cholesterol", AA: "Triglycerides", AB: "Date PF Received", AC: "Dentist ID", AD: "Dentist First Name", AE: "Dentist Last Name", AF: "Dentist Email", AG: "Office Phone", AH: "Date DF Received", AI: "Optometrist ID", AJ: "Optometrist First Name", AK: "Optometrist Last Name", AL: "Optometrist Email", AM: "Office Phone", AN: "Date OVF Received", AO: "Waist"},
    BIOMETRIC_HEALTH_REQUEST_DROP_DATA: {P: "Height", Q: "Weight", R: "BMI", S: "Blood Pressure- Systolic", T: "Blood Pressure- Diastolic", U: "Fasting or Random", V: "Glucose", W: "A1C", X: "Total Cholesterol", Y: "HDL Cholesterol", Z: "LDL Cholesterol", AA: "Triglycerides", AO: "Waist"},
    WEIGHT_REQUEST_HEADER_DATA: {A: 'User ID',B: 'Organization ID',C: 'Username',D: 'First Name',E: 'Middle Name',F: 'Last Name',G: 'Social Security Number',H: 'Employee ID',I: 'Gender',J: 'Birth Date',K: 'Email'},
    HRA_ASSESSMENT_BIOMETRIC_TEXT : [
        {"low_risk": "assementtext_low_risk_1_", "mod_risk": "assementtext_mod_risk_1_", "high_risk": "assementtext_high_risk_1_", "very_high_risk": "assessment_text_very_high_risk_1_", "learn_more": "assementtext_learn_more_1_", "path": "assessment_text"},
        {"low_risk": "assementtext_low_risk_2_", "mod_risk": "assementtext_mod_risk_2_", "high_risk": "assementtext_high_risk_2_", "very_high_risk": "assessment_text_very_high_risk_2_", "learn_more": "assementtext_learn_more_2_", "path": "assessment_text"},
        {"low_risk": "assementtext_low_risk_3_", "mod_risk": "assementtext_mod_risk_3_", "high_risk":  "assementtext_high_risk_3_", "very_high_risk": "assessment_text_very_high_risk_3_", "learn_more": "assementtext_learn_more_3_", "path": "assessment_text"},
        {"low_risk": "assementtext_low_risk_4_", "mod_risk": "assementtext_mod_risk_4_", "high_risk":  "assementtext_high_risk_4_", "very_high_risk": "assessment_text_very_high_risk_4_", "learn_more": "assementtext_learn_more_4_", "path": "assessment_text"},
        {"low_risk": "assementtext_low_risk_5_", "mod_risk": "assementtext_mod_risk_5_", "high_risk":  "assementtext_high_risk_5_", "very_high_risk": "assessment_text_very_high_risk_5_", "learn_more": "assementtext_learn_more_5_", "path": "assessment_text"},
        {"low_risk": "Glucose_GlowRisk_", "mod_risk": "Glucose_GPrediabetes_", "high_risk": "Glucose_GHighRisk_", "very_high_risk": "glucose_very_high_risk_", "learn_more": "Glucose_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "BloodPressure_BLowRisk_", "mod_risk": "BloodPressure_BPrehypertension_", "high_risk": "BloodPressure_BIHypertension_", "very_high_risk": "BloodPressure_BIIHypertension_", "learn_more": "BloodPressure_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "BloodPressureDiastolic_BLowRiskdiastolic_", "mod_risk": "BloodPressureDiastolic_BPrehypertensiondiastolic_", "high_risk": "BloodPressureDiastolic_BIHypertensiondiastolic_", "very_high_risk": "BloodPressureDiastolic_BIIHypertensiondiastolic_", "learn_more": "BloodPressureDiastolic_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "BMI_BMILowRisk_", "mod_risk": "BMI_BMIModerateRisk_", "high_risk": "BMI_BMIHighRisk_", "very_high_risk": "BMI_BMIVeryHigh_", "learn_more": "BMI_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "TotalCholesterol_CHOLLowRisk_", "mod_risk": "TotalCholesterol_CHOLModerateRisk_", "high_risk": "TotalCholesterol_CHOLHighRisk_", "very_high_risk": "total_cholesterol_very_high_risk_", "learn_more": "TotalCholesterol_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "LDLCholesterol_LDLLowRisk_", "mod_risk": "LDLCholesterol_LDLModerateRisk_", "high_risk": "LDLCholesterol_LDLHighRisk_", "very_high_risk": "LDLCholesterol_LDLVeryHigh_", "learn_more": "LDLCholesterol_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "HDLCholesterolMen_MHDLLowRisk_", "mod_risk": "HDLCholesterolMen_MHDLMediumRisk_", "high_risk": "HDLCholesterolMen_MHDLHighRisk_", "very_high_risk": "hdl_cholesterol_men_very_high_risk_", "learn_more": "HDLCholesterolMen_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "HDLCholesterolWomen_WHDLLowRisk_", "mod_risk": "HDLCholesterolWomen_WHDLMediumRisk_", "high_risk": "HDLCholesterolWomen_WHDLHighRisk_", "very_high_risk": "hdl_cholesterol_women_very_high_risk_", "learn_more": "HDLCholesterolWomen_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "Tryglicerides_TryLowRisk_", "mod_risk": "Tryglicerides_TryMediumRisk_", "high_risk": "Tryglicerides_TryHighRisk_", "very_high_risk": "Tryglicerides_TryVeryHighRisk_", "learn_more": "Tryglicerides_learnmore_", "path": "biometrocs_text"},
        {"low_risk": "TCHDL_cholHDLLowRisk_", "mod_risk": "a1c_mod_risk_", "high_risk": "a1c_high_risk_", "very_high_risk": "TCHDL_cholHDLAboveAvgRisk_", "learn_more": "TCHDL_learnmore_", "path": "biometrocs_text"},
    ],
    INCENTIVE_REPORT_HEADER: ['USER CODE', 'ORGANIZATION', 'DEPARTMENT', 'RELATIONSHIP ID', 'USERNAME', 'FIRST NAME', 'MIDDLE NAME', 'LAST NAME', 'JOB TITLE', 'EMPLOYEE ID', 'GENDER', 'BIRTH DATE', 'DATE OF HIRE', 'ON HEALTH PLAN', 'HEALTH PLAN NAME', 'EMAIL', 'WORK PHONE NUMBER', 'WORK PHONE EXTENSION', 'LOCATION', 'WORK ADDRESS1', 'WORK ADDRESS2', 'WORK CITY', 'WORK STATE/PROVINCE', 'WORK ZIP/POSTAL CODE', 'WORK COUNTRY', 'HOME PHONE NUMBER', 'MOBILE PHONE NUMBER', 'HOME ADDRESS1', 'HOME ADDRESS2', 'HOME CITY', 'HOME STATE/PROVINCE', 'HOME ZIP/POSTAL CODE', 'HOME COUNTRY', 'USER TYPE'],
    CAMPAIGN_REPORT_HEADER: ['USER CODE', 'ORGANIZATION', 'DEPARTMENT', 'RELATIONSHIP ID', 'USERNAME', 'FIRST NAME', 'MIDDLE NAME', 'LAST NAME', 'JOB TITLE', 'EMPLOYEE ID', 'GENDER', 'BIRTH DATE', 'DATE OF HIRE', 'ON HEALTH PLAN', 'HEALTH PLAN NAME', 'EMAIL', 'WORK PHONE NUMBER', 'WORK PHONE EXTENSION', 'LOCATION', 'WORK ADDRESS1', 'WORK ADDRESS2', 'WORK CITY', 'WORK STATE/PROVINCE', 'WORK ZIP/POSTAL CODE', 'WORK COUNTRY', 'HOME PHONE NUMBER', 'MOBILE PHONE NUMBER', 'HOME ADDRESS1', 'HOME ADDRESS2', 'HOME CITY', 'HOME STATE/PROVINCE', 'HOME ZIP/POSTAL CODE', 'HOME COUNTRY', 'USER TYPE'],
    ORG_CENSUS_REPORT_HEADER: ['Client Name', 'Broker Portal', 'Brokerage Firm Name','Contract start date','Contract end date','Billing Email Addresses','Billing Frequency','Active Campaign (Yes/No)','Participation (completed at least one activity)','Total Number of Employees','Total Number of Spouses','Total Number of Employees On Health Plan','Total Number of Employees Off Health Plan','Last Census Upload','Additional Billing Details','Engagement Manager Name','Package','Billing start date','Billing end date','Date of Expense Submission','Expense Description and Amount'],
    MODULE_ID_REPORT_NAME: {
        1 : 'Incentive',
        2 : 'MyPlan',
        3 : 'Challenge',
        4 : 'COVID19',
        5 : 'Quicklink',
        6 : 'Fitness Video',
        7 : 'Billboards',
        8 : 'Event',
        9 : 'Health',
        10 : 'Activity',
        11 : 'Quiz',
        12 : 'Emotional Well-Being',
        13 : 'Survey',
        14 : 'Engagement Comparison',
        15 : 'Reimbursements',
        16 : 'Biometrics',
    }
};
