export const campaignConstant = {
    DefaultRewards : {
                        "id": 0,
                        "campaign_id": null,
                        "order_id": 0,
                        "reward_name": "Default Reeward",
                        "reward_desc": "",
                        "ins_reward": 0,
                        "ins_ids": "",
                        "cash_reward": 0,
                        "cash_ids": "",
                        "other_reward": 0,
                        "other_ids": "",
                        "related_activity": "",
                        "related_challenge": "",
                        "related_category": "",
                        "cat_activity_visibility": 0,
                        "hire_date": 0,
                        "user_eligible": 0,
                        "is_display_status": 0,
                        "eligibility": 0,
                        "added_date": "2025-04-14T08:32:38.000Z",
                        "updated_date": "2025-04-14T08:32:38.000Z",
                        "status": 1,
                        "org_tab_setting": "1,2,3,4,5,6,7,8,9,10,11,12,13",
                        "isDefaultReward": 1,
                        'activitys': [
                            {
                                "id": '001',
                                "campaign_id": null,
                                "order_id": 1,
                                "activity_id": 890,
                                "reward_id": 0,
                                "cust_name": "",
                                "cust_description": "",
                                "opentype": 0,
                                "openinternal": 4,
                                "openexternal": "",
                                "video": 0,
                                "quentity": "1",
                                "required_by_user": "N",
                                "required_by_spouse": "N",
                                "frequincy": "D",
                                "frequincy_max_point": "1",
                                "point_for_each": "1",
                                "max_point": "1",
                                "ac_max": null,
                                "ac_min": null,
                                "per_change": null,
                                "alt_activity": null,
                                "alt_act_point": null,
                                "steps": null,
                                "min_act_req_camp": 0,
                                "source_type": 0,
                                "count_type": 0,
                                "category_visibility": 0,
                                "is_display_status": 0,
                                "is_hidden_on_activity_page": 0,
                                "start_date": "2025-02-01 00:00:00",
                                "end_date": "2026-12-31 00:00:00",
                                "added_date": "2025-04-14T08:50:32.000Z",
                                "updated_date": "2025-04-14T08:50:32.000Z",
                                "status": 1,
                                "point_end_date": "",
                                "after_deadline_date": "",
                                "consider_after_deadline": 0,
                                "activity": {
                                    "id": 890,
                                    "category_id": 9,
                                    "activity_name": "Web Login",
                                    "accebility": "0",
                                    "plugin": "",
                                    "controller": "",
                                    "action": "",
                                    "ext_link": "",
                                    "description": "",
                                    "enable_activity_tracker": 0,
                                    "enable_reimbursement": 0,
                                    "activity_display": 0,
                                    "is_age_common": 0,
                                    "status": 1,
                                    "created_by": 1,
                                    "added_date": "2016-05-21T18:58:27.000Z",
                                    "updated_date": "2016-05-21T18:58:27.000Z"
                                },
                                "category": {
                                    "id": 9,
                                    "category_name": "Other Activities",
                                    "qty_req": 1,
                                    "reqby_usr": 1,
                                    "reqby_spouse": 1,
                                    "max_freto_earn_point": 1,
                                    "point_for_each": 1,
                                    "max_point_per_cham": 1,
                                    "orgenization_code": null,
                                    "description": null,
                                    "plugin": null,
                                    "controller": null,
                                    "action": null,
                                    "ext_link": null,
                                    "status": 1,
                                    "added_date": "2014-12-10T03:10:08.000Z",
                                    "updated_date": "2014-12-10T03:10:08.000Z"
                                }
                            },
                            {
                                "id": '002',
                                "campaign_id": null,
                                "order_id": 2,
                                "activity_id": 12748,
                                "reward_id": 2109,
                                "cust_name": "",
                                "cust_description": "",
                                "opentype": 0,
                                "openinternal": 4,
                                "openexternal": "",
                                "video": 0,
                                "quentity": "1",
                                "required_by_user": "N",
                                "required_by_spouse": "N",
                                "frequincy": "D",
                                "frequincy_max_point": "1",
                                "point_for_each": "1",
                                "max_point": "1",
                                "ac_max": null,
                                "ac_min": null,
                                "per_change": null,
                                "alt_activity": null,
                                "alt_act_point": null,
                                "steps": null,
                                "min_act_req_camp": 0,
                                "source_type": 0,
                                "count_type": 0,
                                "category_visibility": 0,
                                "is_display_status": 0,
                                "is_hidden_on_activity_page": 0,
                                "start_date": "2025-02-01 00:00:00",
                                "end_date": "2026-12-31 00:00:00",
                                "added_date": "2025-04-14T08:50:32.000Z",
                                "updated_date": "2025-04-14T08:50:32.000Z",
                                "status": 1,
                                "point_end_date": "",
                                "after_deadline_date": "",
                                "consider_after_deadline": 0,
                                "activity": {
                                    "id": 12748,
                                    "category_id": 9,
                                    "activity_name": "App Login",
                                    "accebility": "0",
                                    "plugin": "",
                                    "controller": "",
                                    "action": "",
                                    "ext_link": "",
                                    "description": "",
                                    "enable_activity_tracker": 0,
                                    "enable_reimbursement": 0,
                                    "activity_display": 0,
                                    "is_age_common": 0,
                                    "status": 1,
                                    "created_by": 1,
                                    "added_date": "2023-05-23T04:23:56.000Z",
                                    "updated_date": "2023-05-23T04:23:56.000Z"
                                },
                                "category": {
                                    "id": 9,
                                    "category_name": "Other Activities",
                                    "qty_req": 1,
                                    "reqby_usr": 1,
                                    "reqby_spouse": 1,
                                    "max_freto_earn_point": 1,
                                    "point_for_each": 1,
                                    "max_point_per_cham": 1,
                                    "orgenization_code": null,
                                    "description": null,
                                    "plugin": null,
                                    "controller": null,
                                    "action": null,
                                    "ext_link": null,
                                    "status": 1,
                                    "added_date": "2014-12-10T03:10:08.000Z",
                                    "updated_date": "2014-12-10T03:10:08.000Z"
                                }
                            }
                        ],
                    },
    GenderData: {
                    'm' : {
                        "id": 1,
                        "gender_name": "Male",
                        "status": 1,
                        "complete": 0,
                        "completePer": 0,
                        "EngDifference": '- - -',
                        "EngDifferencePer": '- - -'
                    },
                    'f' : {
                        "id": 2,
                        "gender_name": "Female",
                        "status": 1,
                        "complete": 0,
                        "completePer": 0,
                        "EngDifference": '- - -',
                        "EngDifferencePer": '- - -'
                    },
                    'o' : {
                        "id": 3,
                        "gender_name": "Other",
                        "status": 1,
                        "complete": 0,
                        "completePer": 0,
                        "EngDifference": '- - -',
                        "EngDifferencePer": '- - -'
                    }
                },
    AgeGroupData : {
        1 : {
            "id": 1,
            "age_group": "18-25",
            "min_age": 18,
            "max_age": 25,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        2 : {
            "id": 2,
            "age_group": "26-35",
            "min_age": 26,
            "max_age": 35,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        3 : {
            "id": 3,
            "age_group": "36-45",
            "min_age": 36,
            "max_age": 45,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        4 : {
            "id": 4,
            "age_group": "46-55",
            "min_age": 46,
            "max_age": 55,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        5 : {
            "id": 5,
            "age_group": "56-65",
            "min_age": 56,
            "max_age": 65,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        6 : {
            "id": 6,
            "age_group": "66+",
            "min_age": 66,
            "max_age": null,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        },
        7 : {
            "id": 7,
            "age_group": "45+",
            "min_age": 45,
            "max_age": null,
            "complete": 0,
            "completePer": 0,
            "EngDifference": '- - -',
            "EngDifferencePer": '- - -'
        }
    },
    CAMPAIGN_TAB_SETTING : [
        { id: 1, label: 'Combined (all employees & spouses on/off plan-entire company)' },
        { id: 2, label: 'Employees (all employees within the company)' },
        { id: 3, label: 'Spouses (all spouses within the company)' },
        { id: 4, label: 'On health plan (employee)' },
        { id: 5, label: 'Off health plan (employee)' },
        { id: 6, label: 'On health plan (spouse)' },
        { id: 7, label: 'Off health plan (spouse)' },
        { id: 8, label: 'Combined On Health Plan (employee & spouse)' },
        { id: 9, label: 'Combined Off Health Plan (employee & spouse)' },
        { id: 10, label: 'Location' },
        { id: 11, label: 'Department' },
        { id: 12, label: 'Gender' },
        { id: 13, label: 'Age Group' }
    ]
};