export const cronServiceTableConstant = {
    TABLES: {
        re_covid19_reports: 'covid_report',
        re_quicklink_reports: 'quicklink_report',
        re_fitnessvideo_reports: 'fod_report',
        re_emotionalwellbeing_reports: 'ewb_report',
        re_survey_reports: 'survey_report',
        re_activity_reports: 'activity_report',
        re_reimbursements_reports: 'reimbursements_report',
        in_incentive_reports: 'in_ch_plan_reports',
        re_event_reports: 'event_report',
        re_quiz_reports: 'quiz_report',
        re_health_reports: 'health_checkup_report',
        biometric_result_report: 'biometric_result_report',
        eha_detail_report: 'eha_detail_report',
        hra_detail_report: 'hra_detail_report',
        engagement_comparison_report: 'engagement_comparison_report',
        c_companydashboards:'billboard_report'
    },
    AUTOREPORTTABLES:{
        in_incentive_reports: 'in_ch_plan_reports',
        re_covid19_reports: 'covid_report',
        re_quicklink_reports: 'quicklink_report',
        re_fitnessvideo_reports: 'fod_report',
        c_companydashboards:'billboard_report',
        re_event_reports: 'event_report',
        re_health_reports: 'health_checkup_report',
        re_activity_reports: 'activity_report',
        re_quiz_reports: 'quiz_report',
        re_emotionalwellbeing_reports: 'ewb_report',
        re_survey_reports: 'survey_report',
        engagement_comparison_report: 'engagement_comparison_report',
        re_reimbursements_reports: 'reimbursements_report',
        biometric_result_report: 'biometric_result_report',
    },
    REPORTFROMMODULEIDS: {
        1: 'in_ch_plan_reports',
        // 2: in_ch_plan_reports,
        // 3: in_ch_plan_reports,
        4: 'covid_report',
        5: 'quicklink_report',
        6: 'fod_report',
        7: 'billboard_report',
        8: 'event_report',
        9: 'health_checkup_report',
        10: 'activity_report',
        11: 'quiz_report',
        12: 'ewb_report',
        13: 'survey_report',
        14: 'engagement_comparison_report',
        15: 'reimbursements_report',
        16: 'biometric_result_report',
    }
};
