export const errorConstantKeys = {
    ERR_INTERNAL_SERVER_ERROR: "ERR_INTERNAL_SERVER_ERROR",
    ERR_MISSING_AUTHORIZATION: 'ERR_MISSING_AUTHORIZATION',
    ERR_EXPIRED_AUTHORIZATION: 'ERR_EXPIRED_AUTHORIZATION',
    ERR_IMAGE_SIZE: 'ERR_IMAGE_SIZE',
    ERR_FILE_LIMIT: "ERR_FILE_LIMIT",
    ERR_FILE_SIZE: 'ERR_FILE_SIZE',
    ERR_IMAGE_TYPE: 'ERR_IMAGE_TYPE',
    ERR_ACCESS_DENIED: 'ERR_ACCESS_DENIED',
    ERR_REQUIRED_PARAM_MISSING: 'ERR_REQUIRED_PARAM_MISSING',
    ERR_ACTIVITY_NOT_FOUND: 'ERR_ACTIVITY_NOT_FOUND',
    ERR_SOMETHING_WENT_WRONG: 'ERR_SOMETHING_WENT_WRONG',
    ERR_CAMPAIGN_EXIST: 'ERR_CAMPAIGN_EXIST',
    ERR_CAMPAIGN_RECORD_NOT_FOUND: 'ERR_CAMPAIGN_RECORD_NOT_FOUND',
    ERR_TOO_MANY_REQUEST: 'ERR_TOO_MANY_REQUEST',
    ERR_INVALID_LOGIN: 'ERR_INVALID_LOGIN',
    ERR_RECORD_NOT_FOUND: 'ERR_RECORD_NOT_FOUND',
    ERR_INVALID_VALUE_PARAM: 'ERR_INVALID_VALUE_PARAM',
    ERR_FORBIDDEN_ACCESS: 'ERR_FORBIDDEN_ACCESS',
    ERR_DUPLICATE_ENTRY: 'ERR_DUPLICATE_ENTRY',
    COMPANIES: {
        ERR_COMPANY_NAME_EXIST: 'ERR_COMPANY_NAME_EXIST',
        ERR_DEPARTMENT_NAME_EXIST: 'ERR_DEPARTMENT_NAME_EXIST',
        ERR_LOCATION_NAME_EXIST: 'ERR_LOCATION_NAME_EXIST',
    },
    INCENTIVE: {
        ERR_INSURANCE_PLAN_NAME_EXIST: 'ERR_INSURANCE_PLAN_NAME_EXIST',
    },
    ERR_USER_EMAIL_EXIST: 'ERR_USER_EMAIL_EXIST',
    ERR_USERNAME_EXIST: 'ERR_USERNAME_EXIST',
    ERR_PASSWORD_EXIST: 'ERR_PASSWORD_EXIST',
    ERR_FILES_ALREADY_EXIST: 'ERR_FILES_ALREADY_EXIST',
    ERR_FIELS_ALREADY_EXIST: 'ERR_FIELS_ALREADY_EXIST',
    ERR_TITLE_VALIDATION: 'ERR_TITLE_VALIDATION',
    ERR_VALUE_VALIDATION: 'ERR_VALUE_VALIDATION',
    ERR_SELECT_VALIDATION: 'ERR_SELECT_VALIDATION',
    ERR_FILE_VALIDATION: 'ERR_FILE_VALIDATION',
    ERR_COPY_FIELD: 'ERR_COPY_FIELD',
    ERR_DATA_FILE_TYPE: 'ERR_DATA_FILE_TYPE',
    ERR_DOB_VALIDATION: 'ERR_DOB_VALIDATION',
    ERR_EXCEED_RETAKES: 'ERR_EXCEED_RETAKES',
    ERR_ASSIGN_PLAN_ALREADY_EXIST: 'ERR_ASSIGN_PLAN_ALREADY_EXIST',
    ERR_CHAT_TYPE: 'ERR_CHAT_TYPE',
    ERR_DESCRIPTION_ALREADY_EXIST: 'ERR_DESCRIPTION_ALREADY_EXIST',
    ERR_MEMBERID_NOT_FOUND: 'ERR_MEMBERID_NOT_FOUND',
    ERR_MEMBERID_NOT_FOUND_VALIDATE: 'ERR_MEMBERID_NOT_FOUND_VALIDATE',
    ERR_INVALID_FORM_ID: 'ERR_INVALID_FORM_ID',
    ERR_HEIGHT_REQUIRED: 'ERR_HEIGHT_REQUIRED',
    ERR_HEIGHT_WEIGHT_REQUIRED: 'ERR_HEIGHT_WEIGHT_REQUIRED',
    ERR_DIASTOLIC_SYSTOLIC_REQUIRED: 'ERR_DIASTOLIC_SYSTOLIC_REQUIRED',
    ERR_PREVENTATIVE_CARE_NOT_FOUND: 'ERR_PREVENTATIVE_CARE_NOT_FOUND',
    ERR_NO_TOBACCO_NOT_FOUND: 'ERR_NO_TOBACCO_NOT_FOUND',
    ERR_REPORT_ALREADY_REQUESTED: 'ERR_REPORT_ALREADY_REQUESTED',
    ERR_NO_USER_FOUND: 'ERR_NO_USER_FOUND',
    ERR_INVALID_DATE_RANGE: 'ERR_INVALID_DATE_RANGE',
    ERR_PROGRAM_NOT_FOUND: 'ERR_PROGRAM_NOT_FOUND',
    ERR_PROGRAM_NOT_SETUP: 'ERR_PROGRAM_NOT_SETUP',
};
export const errorConstant = {
    ERR_INTERNAL_SERVER_ERROR: 'Something went wrong on our end. Please try again later.',
    ERR_MISSING_AUTHORIZATION: 'Authorization is missing. Please log in and try again.',
    ERR_EXPIRED_AUTHORIZATION: `You've been signed out. Please log in again.`,
    ERR_IMAGE_SIZE: 'Image exceeds maximum size limit of %sMB. Please choose a smaller image.',
    ERR_FILE_LIMIT: "You can upload a maximum of %s files only.",
    ERR_FILE_SIZE: 'File exceeds the maximum size limit of %sMB. Please choose a smaller file.',
    ERR_IMAGE_TYPE: 'Error Unsupported file format. Please upload a JPG, PNG, or JPEG file.',
    ERR_ACCESS_DENIED: 'Access denied. You do not have permission to perform this action.',
    ERR_REQUIRED_PARAM_MISSING: 'A required field is missing. Please check and try again.',
    ERR_ACTIVITY_NOT_FOUND: 'Activity not found.',
    ERR_SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
    ERR_CAMPAIGN_EXIST: 'Campaign with the same values already exists.',
    ERR_CAMPAIGN_RECORD_NOT_FOUND: 'Campaign record not found.',
    ERR_CHAT_TYPE: 'Chat type is missing or invalid. Please select a valid option.',
    ERR_TOO_MANY_REQUEST: 'Rate limit exceeded. Please try again later.',
    ERR_INVALID_LOGIN: 'Your login credentials are incorrect.',
    ERR_RECORD_NOT_FOUND: 'No records found matching your search.',
    ERR_INVALID_VALUE_PARAM: 'The value you entered is not allowed.',
    ERR_FORBIDDEN_ACCESS: 'Apologies, the URL you requested is not accessible.',
    ERR_DUPLICATE_ENTRY: 'Duplicate data identified. Please rectify.',
    COMPANIES: {
        ERR_COMPANY_NAME_EXIST: 'Company with the same name already exists.',
        ERR_DEPARTMENT_NAME_EXIST: 'Department with the same name already exists.',
        ERR_LOCATION_NAME_EXIST: 'Location with the same values already exists.',
    },
    INCENTIVE: {
        ERR_INSURANCE_PLAN_NAME_EXIST: 'Insurance plan with the same name already exists.',
    },
    ERR_USER_EMAIL_EXIST: 'User with the same email already exists.',
    ERR_USERNAME_EXIST: 'The username you entered is already in use.',
    ERR_PASSWORD_EXIST: 'This password had already been used. Please choose a different one.',
    ERR_FILES_ALREADY_EXIST: '%s already exists.',
    ERR_TITLE_VALIDATION: 'Please enter a %s title.',
    ERR_VALUE_VALIDATION: 'Please enter a %s value.',
    ERR_SELECT_VALIDATION: 'Please select a %s value.',
    ERR_FILE_VALIDATION: 'Please add a %s file.',
    ERR_COPY_FIELD: 'The %s could not be copied. Please try again.',
    ERR_DATA_FILE_TYPE: "Unsupported file format. Please upload a CSV, XLSX, or XLS file.",
    ERR_DOB_VALIDATION: "Please enter a valid date of birth.",
    ERR_EXCEED_RETAKES: "You are not eligible for this quiz.",
    ERR_ASSIGN_PLAN_ALREADY_EXIST: 'This plan is already assigned. Please select a different one.',
    ERR_DESCRIPTION_ALREADY_EXIST: 'Data for this module and organisation already exists.',
    ERR_MEMBERID_NOT_FOUND: "Please enter a valid patient's Member ID or User ID. Or, there is no active Physician Program for this user.",
    ERR_MEMBERID_NOT_FOUND_VALIDATE: "Please enter a valid patient's Member ID or User ID.",
    ERR_INVALID_FORM_ID: "This form ID is not valid for the selected diseases in your organisation.",
    ERR_HEIGHT_REQUIRED: "Height field is required.",
    ERR_HEIGHT_WEIGHT_REQUIRED: "Please enter both height and weight to calculate BMI.",
    ERR_DIASTOLIC_SYSTOLIC_REQUIRED: "Please enter both systolic and diastolic values.",
    ERR_PREVENTATIVE_CARE_NOT_FOUND: "No biometrics or preventative care data found for this user's organization.",
    ERR_NO_TOBACCO_NOT_FOUND: "No tobacco certification found for this user's organisation.",
    ERR_REPORT_ALREADY_REQUESTED: "Your one report request is in progress, we will notify you once the report is available to request",
    ERR_NO_USER_FOUND: "No user found.",
    ERR_INVALID_DATE_RANGE: "Please enter a valid date range.",
    ERR_PROGRAM_NOT_FOUND: "Program not found",
    ERR_PROGRAM_NOT_SETUP: "Program data is not set up. Please configure it first.",
};
