export const timezoneConstant = {
    TIMEZONE: {
        "GMT -12:00": "Pacific/Kwajalein",
        "GMT -11:00": "Pacific/Samoa",
        "GMT -10:00": "Pacific/Honolulu",
        "GMT -09:00": "America/Anchorage",
        "GMT -08:00": "America/Los_Angeles",
        "GMT -07:00": "America/Denver",
        "GMT -06:00": "America/Chicago",
        "GMT -05:00": "America/New_York",
        "GMT -04:00": "Atlantic/Bermuda",
        "GMT -03:30": "Canada/Newfoundland",
        "GMT -03:00": "Brazil/East",
        "GMT -02:00": "Atlantic/Azores",
        "GMT -01:00": "Atlantic/Cape_Verde",
        "GMT": "Europe/London",
        "GMT +01:00": "Europe/Brussels",
        "GMT +02:00": "Europe/Helsinki",
        "GMT +03:00": "Asia/Baghdad",
        "GMT +03:30": "Asia/Tehran",
        "GMT +04:00": "Asia/Baku",
        "GMT +04:30": "Asia/Kabul",
        "GMT +05:00": "Asia/Karachi",
        "GMT +05:30": "Asia/Calcutta",
        "GMT +06:00": "Asia/Dhaka",
        "GMT +07:00": "Asia/Bangkok",
        "GMT +08:00": "Asia/Hong_Kong",
        "GMT +09:00": "Asia/Tokyo",
        "GMT +09:30": "Australia/Adelaide",
        "GMT +10:00": "Pacific/Guam",
        "GMT +11:00": "Asia/Magadan",
        "GMT +12:00": "Pacific/Fiji",
    }
};