import { Allow } from 'class-validator';
export class CreateAssessmentsInput {
    @Allow() id: number;
    @Allow() user_id: number;
    @Allow() activity_id: number;
    @Allow() date: string;
    @Allow() '1': string;
    @Allow() '1_qscore': number;
    @Allow() '1_WorstScore': number;
    @Allow() '2': string;
    @Allow() '2_qscore': number;
    @Allow() '2_WorstScore': number;
    @Allow() '3': string;
    @Allow() '3_qscore': number;
    @Allow() '3_WorstScore': number;
    @Allow() '4': string;
    @Allow() '4_qscore': number;
    @Allow() '4_WorstScore': number;
    @Allow() '5': string;
    @Allow() '5_qscore': number;
    @Allow() '5_WorstScore': number;
    @Allow() '6': string;
    @Allow() '6_qscore': number;
    @Allow() '6_WorstScore': number;
    @Allow() '7': string;
    @Allow() '8': string;
    @Allow() '9': string;
    @Allow() score: number;
    @Allow() na: string;
    @Allow() hra_status: number;
    @Allow() hra_reset: number;
    @Allow() language_set: number;
    @Allow() status: number;
}
