import { Allow } from 'class-validator';
export class CreateDaysUsersInput {
    @Allow() schedule_id: number;
    @Allow() user_id: number;
    @Allow() week_id: number;
    @Allow() day_id: number;
    @Allow() activity_id: number;
    @Allow() challenge_id: number;
    @Allow() site_activity_desc: string;
    @Allow() manual_activity: string;
    @Allow() manual_desc: string;
    @Allow() completion_status: string;
    @Allow() log_status: string;
    @Allow() linkstatus: number;
    @Allow() meal: string;
    @Allow() amount: string;
    @Allow() quantity: string;
    @Allow() steps: string;
    @Allow() duration: string;
    @Allow() distance: string;
    @Allow() calories: string;
    @Allow() tabacco_status: string;
    @Allow() avalue: string;
    @Allow() waterlogunit: string;
    @Allow() m_numeric: string;
    @Allow() m_short: string;
    @Allow() m_long: string;
    @Allow() m_yesno: string;
    @Allow() m_check: string;
    @Allow() m_field: string;
    @Allow() start_date: number;
    @Allow() end_date: number;
    @Allow() status: number;
}
