export * from './assignquizorgs.dto';
export * from './categories.dto';
export * from './fillupquestions.dto'
export * from './hotspotquestions.dto'
export * from './matchingdragdropquestions.dto'
export * from './matchingdropdownquestions.dto'
export * from './multiplechoicequestions.dto'
export * from './multiplequestions.dto'
export * from './multipleresponsequestions.dto'
export * from './quizclicks.dto'
export * from './quizdetails.dto'
export * from './quizorgs.dto'
export * from './quizsections.dto'
export * from './quizuserdetails.dto'
export * from './quizzes.dto'
export * from './truefalsequestions.dto'
export * from './userdetails.dto';
export * from './quizwebinar.dto';
