import { Allow } from 'class-validator';
export class CreateCompanyMetaInput {
    @Allow() id: number;
    @Allow() org_id: number;
    @Allow() custom_text: string;
    @Allow() website: string;
    @Allow() information: string;
    @Allow() agreement_text: string;
    @Allow() due_date_text: string;
    @Allow() a_popup_title: string;
    @Allow() a_popup_text: string;
    @Allow() a_popup_status: number;
    @Allow() a_popup_default_status: number;
    @Allow() a_popup_require: number;
    @Allow() a_popup_logo_status: number;
    @Allow() sso_dtext: string;
    @Allow() sso_dlink: string;
    @Allow() enable_widget: string;
    @Allow() user_popup_title: string;
    @Allow() plan_label: string;
    @Allow() zip_report_password: string;
    @Allow() title: string;
    @Allow() setting_dic: string;
    @Allow() newsletterthemecolors: string;
    @Allow() selectedweeks: string;
    @Allow() selectedmonths: string;
    @Allow() created_by: number;
    @Allow() updated_by: number;
    @Allow() type: string;
    @Allow() completion: string;
    @Allow() required: string;
    @Allow() optional: string;
    @Allow() incomplete: string;
    @Allow() plantext: string;
}
