export interface ThemeSettingInterface{
  id: number;
  theme_id?: number;
  org_id?: number;
  themetype?: string;
  iscustomized?: number;
  bodycolor?: string;
  bodyfontcolor?: string;
  pagecontentbgcolor?: string;
  headercolor?: string;
  mainnavigationactive?: string;
  subnavigationactive?: string;
  submenufontcolor?: string;
  navigationfontcolor?: string;
  pagetitlebgcolor?: string;
  mainpagetitlecolor?: string;
  pagetitlecolor?: string;
  innercontentcolor?: string;
  breadbgcolor?: string;
  breadfontcolor?: string;
  linkcolor?: string;
  sidetogcolor?: string;
  successbgcolor?: string;
  successfontcolor?: string;
  errorbgcolor?: string;
  errorfontcolor?: string;
  btndarkbgcolor?: string;
  btndarkhovercolor?: string;
  btngreenbgcolor?: string;
  btngreenhovercolor?: string;
  bodywithallcolor?: string;
  navigationallcolor?: string;
  esubnavigationactive?: string;
  pagewithallcolor?: string;
  spointtrackbgwarningcolor?: string;
  spointtrackbgsuccesscolor?: string;
  spointtrackfontlabelcolor?: string;
  spointtrackbglabelcolor?: string;
  pointtrackfontsuccesscolor?: string;
  pointtrackbgsuccesscolor?: string;
  pointtrackfontwarningcolor?: string;
  pointtrackbgwarningcolor?: string;
  pointtrackcolor?: string;
  added_date?: string; // or Date if parsed
  updated_date?: string; // or Date if parsed
  reference_id?: number;
  added_by?: number;
  status?: number;
}
