import { Allow } from 'class-validator';
export class CreateCompanyCEMInfoInput {
    @Allow() id: number;
    @Allow() org_id: number;
    @Allow() client_names: string;
    @Allow() client_emails: string;
    @Allow() broker_names: string;
    @Allow() broker_emails: string;
    @Allow() program_description: string;
    @Allow() program_deadline: string;
    @Allow() incentive: string;
    @Allow() spouses: string;
    @Allow() communications: string;
    @Allow() census_notes: string;
    @Allow() wellness_meeting: string;
    @Allow() medical_carrier_tpa: string;
    @Allow() funding_level: string;
    @Allow() wellness_funds: string;
    @Allow() employee_benefits: string;
    @Allow() file_notes: string;
    @Allow() wellness_vendor_notes: string;
    @Allow() wellness_committee: string;
    @Allow() other_notes: string;
    @Allow() ooo_start_date: string;
    @Allow() ooo_end_date: string;
    @Allow() ooo_coverage: string;
    @Allow() ooo_auto_email: string;
    @Allow() created_by: number;
    @Allow() updated_by: number;
    @Allow() created: string;
    @Allow() updated: string;
}
