import { appConstant, CacheService, CommonArrayService, CommonDateService, CommonService } from '@common-constants';
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { AppActivityLogConfigModule } from './config/app-config.module';
import { AppActivityLogConfigProvider } from './config/app-config.provider';
import { EmailLogEntity, ErrorLogEntity } from './entity';
import {
    EmailLogService,
    ErrorLogService
} from './module';
@Module({
    imports: [
        ConfigModule.forRoot({ isGlobal: true }),
        TypeOrmModule.forRootAsync({
            imports: [AppActivityLogConfigModule],
            name: appConstant.MAIN.toLowerCase(),
            useFactory: (configService: AppActivityLogConfigProvider) => {
                return { ...configService.typeOrmConfig, name: configService.typeOrmConfig.name };
            },
            inject: [AppActivityLogConfigProvider],
        }),
        TypeOrmModule.forRootAsync({
            imports: [AppActivityLogConfigModule],
            name: appConstant.READ_REPLICA.toLowerCase(),
            useFactory: (configService: AppActivityLogConfigProvider) => {
                return { ...configService.typeOrmConfig1, name: configService.typeOrmConfig1.name };
            },
            inject: [AppActivityLogConfigProvider],
        }),
        TypeOrmModule.forFeature([
            ErrorLogEntity,
            EmailLogEntity,
        ],appConstant.READ_REPLICA.toLowerCase()),
        TypeOrmModule.forFeature([
            ErrorLogEntity,
            EmailLogEntity,
        ],appConstant.MAIN.toLowerCase()),
    ],
    controllers: [AppController],
    providers: [
        AppService,
        CommonService,
        CommonArrayService,
        CommonDateService,
        CacheService,
        // CommonFileService,
        // CommonHealthService,
        // CsvService,
        // TimezoneService,
        // HtmlTagService,
        // ActivityService,
        // ActivityTrackerService,
        // UpComingActivityService,
        // BiometricService,
        // BiometricOtherService,
        // BrokerService,
        // CensusService,
        // ChallengeService,
        // ChallengeActivityService,
        // ChallengeChatService,
        // ChallengeDayService,
        // ChallengeDayWeekUserService,
        // ChallengeInviteService,
        // ChallengeOtherService,
        // ChallengeScheduleService,
        // ChallengeSquareService,
        // ChallengeTeamService,
        // ChallengeTeamMembersService,
        // ChallengeTeamScheduleService,
        // ChallengeUserActivityService,
        // ChallengeWeekService,
        // ScheduleChallengeJoinUserService,
        // ClaimService,
        // CoachService,
        // CommonService,
        // CommunicationService,
        // CompanyService,
        // CompanyDashboardService,
        // CompanyDepartmentLocationService,
        // CompanyInterlinksService,
        // CompanyOtherService,
        // CompanyReportMenuService,
        // CompanySideMenuService,
        // CompanySupportService,
        // CovidService,
        // ClientManagerAssignService,
        // DataManagementService,
        // DeviceConfigurationService,
        // DiseaseManagementService,
        // EmotionalWellbeingService,
        // EmotionalWellbeingPostService,
        // EventService,
        // EventDepartmentLocationService,
        // EventOtherService,
        // EventSlotService,
        // EventUserBookingListService,
        // HaEmotionalAssessmentService,
        // HaEmotionalAssessmentResultService,
        // HaHealthAssessmentService,
        // HealthAssessmentService,
        // HealthAssessmentAnswersService,
        // HealthAssessmentDetailsService,
        // HealthAssessmentOtherService,
        // HealthAssessmentResultService,
        // HealthCheckupService,
        // HealthCheckupFormInstructionService,
        // HealthCheckupTobaccoUsesService,
        // HealthCheckupUserFormService,
        // IncentiveService,
        // IncentiveCampaignService,
        // IncentiveCampaignActivityService,
        // IncentiveCampaignCategoryService,
        // IncentiveCampaignChallengeService,
        // IncentiveCampaignRewardService,
        // IncentiveCashRewardService,
        // IncentiveCustomPointService,
        // IncentiveOtherRewardService,
        // IncentiveSettingService,
        // LanguageService,
        // MediaFitnessOtherService,
        // MediaFitnessPostService,
        // MediaFitnessVideoService,
        // MediaVideoService,
        // MyPlanService,
        // MyPlanAssignUserPlanService,
        // MyPlanCompleteService,
        // MyPlanJoinUserPlanService,
        // MyPlanOtherService,
        // PermissionService,
        // QuickLinkService,
        // QuickLinkOtherService,
        // QuizService,
        // QuizAssignOrgService,
        // QuizDetailsService,
        // QuizOtherService,
        // QuizUserService,
        // ReimbursementService,
        // SurveyService,
        // ThemeService,
        // ActivityFeedService,
        // BodyFeedService,
        // FoodAuthorizedUserService,
        // FoodFeedService,
        // FoodNutritionValueService,
        // UserService,
        // UserOtherService,
        // MembershipPlanService,
        ErrorLogService,
        // DefaultService,
        // CompanyCEMInfoService,
        EmailLogService
    ],
})
export class AppModule {}
