import 'dotenv/config';
export const cronAppConstant = {
    MY_PLAN_REPORT_HRADER_DATA: [
        'ORGANIZATION',
        'DEPARTMENT',
        'RELATIONSHIP ID',
        'USERNAME',
        'FIRST NAME',
        'MIDDLE NAME',
        'LAST NAME',
        'JOB TITLE',
        'SOCIAL SECURITY NUMBER',
        'EMPLOYEE ID',
        'GENDER',
        'BIRTH DATE',
        'DATE OF HIRE',
        'ON HEALTH PLAN',
        'HEALTH PLAN NAME',
        'EMAIL',
        'WORK PHONE NUMBER',
        'WORK PHONE EXTENSION',
        'LOCATION',
        'WORK ADDRESS1',
        'WORK ADDRESS2',
        'WORK CITY',
        'WORK STATE/PROVINCE',
        'WORK ZIP/POSTAL CODE',
        'WORK COUNTRY',
        'HOME PHONE NUMBER',
        'MOBILE PHONE NUMBER',
        'HOME ADDRESS1',
        'HOME ADDRESS2',
        'HOME CITY',
        'HOME STATE/PROVINCE',
        'HOME ZIP/POSTAL CODE',
        'HOME COUNTRY',
        'USER CODE',
        'ELIGIBLE FOR CAMPAIGN',
    ],
    USER_HEADER_DATA: [
        'USER CODE',
        'ORGANIZATION',
        'DEPARTMENT',
        'RELATIONSHIP ID',
        'FIRST NAME',
        'MIDDLE NAME',
        'LAST NAME',
        'JOB TITLE',
        'GENDER',
        'BIRTH DATE',
        'DATE OF HIRE',
        'ON HEALTH PLAN',
        'HEALTH PLAN NAME',
        'EMAIL',
        'LOCATION',
        'USER TYPE',
    ],
    TEAM_HEADER_DATA: [
        'ORGANIZATION', 'TEAM', 'TEAM SIZE', 'TEAM MEMBERS'
    ],
    GROUP_HEADER_DATA: [
        'ORGANIZATION', 'GROUP', 'GROUP TEAMS'
    ],
    BIOMETRIC_RESULT_REPORT_HEADER_DATA: ['UID-ALT','Relationship','DOB','Current Height','Current Weight','Gender','DOH','Med Eff Date','Past Year','Past Screening Date','Past Fasting','Past HDL','Past Trig','Past Gluc','Past BMI','Past Waist','Past Sys','Past Dia','Current Year','Current Screening Date','Current Fasting','Current HDL','Current Trig','Current Gluc','Current BMI','Current Waist','Current Sys','Current Dia'],
    GENDER: { 1: 'Male', 2: 'Female', 3: 'Other' },
    GENDER_MAP: { m: 1, male: 1, f: 2, female: 2, o: 3, other: 3 },
    CAMPAIGN_ELIGIBLE: { 0: 'No', 1: 'Yes' },
    USER_TYPE: { 1: 'Spouse', 2: 'Employee' },
    INSURANCE_PLAN: {
        yes: 'Yes',
        y: 'Yes',
        no: 'No',
        n: 'No',
        o: '',
        other: '',
    },
};
