import 'dotenv/config';
export const appCensusConstant = {
    CENSUS_USER_LIST: [
        'user.id',
        'user.status',
        'user.department_id',
        'user.relationship_id',
        'user.role_id',
        'user.username',
        'user.first_name',
        'user.middle_name',
        'user.last_name',
        'settings.jobtitle',
        'user.securitycode',
        'user.employeeid',
        'user.gender',
        'user.dob',
        'user.date_of_hire',
        'user.on_insurance_plan',
        'user.insurance_plan_name',
        'user.email',
        'settings.wphone',
        'settings.wphone_ext',
        'user.location',
        'settings.hphone',
        'settings.cphone',
        'settings.address',
        'settings.address2',
        'settings.city',
        'settings.state',
        'settings.zip',
        'settings.country',
        'user.code',
        'user.timezone',
        'user.is_camp_eligible',
        'settings.email_receiving',
        'settings.email_update',
        'settings.id',
        'settings.user_id',
    ],
    CENSUS_COMPANY_LIST: [
        'company.company_name',
        'company.code',
        'companySetting.org_id',
        'company.id',
        'companySetting.census_status',
        'companySetting.spouse_option',
        'companySetting.lock_username',
        'companySetting.employee_id',
        'companySetting.is_reqd_empid',
    ],
    genderMap: { m: 'Male', f: 'Female', o: 'Other' },
    insuranceMap: { yes: 'Yes', y: 'Yes', no: 'No', n: 'No' },
    statusMap: {
        1: 'Current',
        2: 'Terminated',
        3: 'Retired',
        4: 'Extended Leave',
    },
    updateCodeMap: {
        middle_name: 1008,
        first_name: 1002,
        last_name: 1003,
        dob: 1004,
        gender: 1005,
        email: 1006,
        wphone: 1007,
        zip: 1011,
        cphone: 1012,
        employeeid: 1013,
        username: 1021,
        status: 1022,
        relationship_code: 1023,
        relationship_id: 1024,
        role_id: 1027,
        id_of_direct_supervisor: 1028,
        date_of_hire: 1029,
        on_insurance_plan: 1030,
        insurance_plan_name: 1031,
        location: 1034,
        code: 1064,
    },
    importantFieldsSet: [
        'jobtitle',
        'wphone',
        'wphone_ext',
        'hphone',
        'cphone',
        'address',
        'address2',
        'email_receiving',
        'email_update',
        'country',
        'state',
        'city',
        'zip',
    ],
    partialErrorCodes: {
        1002: 'first_name',
        1003: 'last_name',
        1004: 'dob',
        1006: 'email',
    },
    directAssignField: [
        'department_id',
        'is_camp_eligible',
        'address',
        'address2',
        'wphone_ext',
        'jobtitle',
        'code',
        'securitycode',
    ],
    errorMap: {
        securitycode: 1058,
        employeeid: 1013,
        relationship_id: 1036,
        email: 1006,
        username: 1021,
    },
    codeMap: {
        1058: 'securitycode',
        1013: 'employeeid',
        1036: 'relationship_id',
        1006: 'email',
        1021: 'username',
    },
    fieldsToCheckOr: ['username', 'email', 'securitycode', 'relationship_id'],
    CENSUS_TERMINATE_USER_LIST: [
        'User.id',
        'department.dept_name',
        'location.lname',
        'location.address1',
        'location.address2',
        'location.city',
        'location.state',
        'location.zip',
        'location.country',
        'User.first_name',
        'User.middle_name',
        'User.last_name',
        'User.username',
        'User.email',
        'User.role_id',
        'User.status',
        'User.department_id',
        'User.securitycode',
        'User.employeeid',
        'User.relationship_id',
        'User.insurance_plan_name',
        'User.on_insurance_plan',
        'User.code',
        'User.gender',
        'User.dob',
        'User.date_of_hire',
        'User.is_camp_eligible',
        'settings.wphone',
        'settings.wphone_ext',
        'settings.hphone',
        'settings.cphone',
        'settings.address',
        'settings.address2',
        'settings.city',
        'settings.state',
        'settings.zip',
        'settings.country',
        'settings.jobtitle',
        'settings.email_receiving',
        'settings.email_update',
    ],
    CENSUS_COMPARE_EXCLUDED_KEYS: [
        'compare',
        '__status',
        'tmp',
        'is_spouse_added',
        'relationship_code',
        'work_address_1',
        'work_address_2',
        'work_city',
        'work_state',
        'work_zip',
        'work_country',
        'spouse_first_name',
        'spouse_last_name',
        'spouse_dob',
        'spouse_gender',
        'spouse_email',
        'spouse_on_health_plan',
    ],
};
// app.constants.ts

export const isValidName = (name: string): boolean =>
    /^[a-zA-Z0-9 \s`.'-]+$/.test(name);

export const phonePattern: RegExp =
    /^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*(?![2-9]11)(?!555)([2-9][0-8][0-9])\s*\)|(?![2-9]11)(?!555)([2-9][0-8][0-9]))\s*(?:[.-]\s*)?)(?!(555(?:\s*(?:[.\-\s]\s*))(01([0-9][0-9])|1212)))(?!(555(01([0-9][0-9])|1212)))([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$/;
