import { Allow } from 'class-validator';
export class CreateCoreThemeInput {
    @Allow() themename: string;
    @Allow() themetype: string;
    @Allow() bodycolor: string;
    @Allow() bodyfontcolor: string;
    @Allow() pagecontentbgcolor: string;
    @Allow() headercolor: string;
    @Allow() mainnavigationactive: string;
    @Allow() subnavigationactive: string;
    @Allow() navigationfontcolor: string;
    @Allow() pagetitlebgcolor: string;
    @Allow() mainpagetitlecolor: string;
    @Allow() pagetitlecolor: string;
    @Allow() innercontentcolor: string;
    @Allow() breadbgcolor: string;
    @Allow() breadfontcolor: string;
    @Allow() linkcolor: string;
    @Allow() sidetogcolor: string;
    @Allow() successbgcolor: string;
    @Allow() successfontcolor: string;
    @Allow() errorbgcolor: string;
    @Allow() errorfontcolor: string;
    @Allow() btndarkbgcolor: string;
    @Allow() btndarkhovercolor: string;
    @Allow() btngreenbgcolor: string;
    @Allow() btngreenhovercolor: string;
    @Allow() bodywithallcolor: string;
    @Allow() navigationallcolor: string;
    @Allow() esubnavigationactive: string;
    @Allow() pagewithallcolor: string;
    @Allow() status: number;
}
