export const tableConstant = {
    TBL_DATA_SRC: 'DATA_SRC',
    TBL_DATA_SRCLN: 'DATSRCLN',
    TBL_DERIV_CD: 'DERIV_CD',
    TBL_FD_GROUP: 'FD_GROUP',
    TBL_FOOD_DES: 'FOOD_DES',
    TBL_FOOD_NOTE: 'FOOTNOTE',
    TBL_LANG_DESC: 'LANGDESC',
    TBL_LANGUAL: 'LANGUAL',
    TBL_NUTR_DEF: 'NUTR_DEF',
    TBL_NUT_DATA: 'NUT_DATA',
    TBL_SRC_CD: 'SRC_CD',
    TBL_WEIGHT: 'WEIGHT',
};
