import {
    ActivePluginsEntity,
    ActivityEntity,
    ActivityFeedsEntity,
    AgeActivityEntity,
    AssessmentEmotionalAssessmentAnswerEntity,
    AssessmentEmotionalAssessmentEntity,
    AssessmentHaQuestionsEntity,
    AssessmentHraBiometricEntity,
    AssessmentOptionsEntity,
    AssessmentQuestionsEntity,
    AssessmentResultsEntity,
    AssessmentTabsEntity,
    AssessmentsEntity,
    AuthorizationsEntity,
    AutoReportSettingsEntity,
    BioWeightEntity,
    BiometricEntity,
    BiometricOrgSettingEntity,
    BiometricsEntity,
    BodyFeedsEntity,
    CacheService,
    CampaignActivityEntity,
    CampaignCategoryEntity,
    CampaignChallengeEntity,
    CampaignEntity,
    CampaignRewardEntity,
    CardsEntity,
    CashRewardEntity,
    CategoryEntity,
    CensusCustomFieldsEntity,
    CensusCustomFieldsValuesEntity,
    ChallengeEntity,
    ChallengeExternalLinkEntity,
    CommitmentLevelsEntity,
    CommonArrayService,
    CommonDateService,
    CommonFileService,
    CommonHealthService,
    CommonService,
    CommunicationTemplateTextsEntity,
    CompaniesEntity,
    CompanyMasscommunicationEntity,
    CompanyNumberOfLiveReportsEntity,
    CompanySettingsEntity,
    CompanyReportMenuSettingsEntity,
    CovidQuestionsEntity,
    CovidReportEntity,
    CustomPointEntity,
    CustomPointRequestEntity,
    DataManagementDocumentEntity,
    DentistsEntity,
    DepartmentsEntity,
    DiseaseFormCoverPagesEntity,
    DiseaseFormsEntity,
    DiseasesEntity,
    DownloadFormsEntity,
    EmotionalWellBeingCategoryEntity,
    EmotionalWellBeingPostClickEntity,
    EmotionalWellBeingPostEntity,
    EngagementComparisonReportsEntity,
    EventCategoryEntity,
    EventEntity,
    EventExternalLinkEntity,
    EventGlobalEventsEntity,
    EventUserBookingListsEntity,
    FitnessActivityEntity,
    FoodFeedsEntity,
    FormInstructionsEntity,
    FormSendRequestUserEntity,
    FtBiometricsEntity,
    HealthActivityEntity,
    HealthRequestEntity,
    HealthUsersActivityEntity,
    ImportUserRequestEntity,
    IncentiveReportsEntity,
    InsuranceRewardEntity,
    InterlinksEntity,
    LocationsEntity,
    MediaFitnessVideoClickEntity,
    MediaFitnessVideosEntity,
    MediaFitnessVideosReportEntity,
    MoveMoreParksEntity,
    MyPlanActivityEntity,
    MyPlanAssignPlanEntity,
    MyPlanAssignRuleEntity,
    MyPlanAssignUserPlanEntity,
    MyPlanBlocksEntity,
    MyPlanCompleteActivityEntity,
    MyPlanCompleteBlockEntity,
    MyPlanJoinUserPlanEntity,
    MyPlanPlansEntity,
    OptometristsEntity,
    OrgBiometricEntity,
    OtherRewardEntity,
    PhysicianTempsEntity,
    QuickLinkClicksEntity,
    QuickLinkEntity,
    QuickLinkReReportEntity,
    QuickLinkReportEntity,
    QuizDetailsEntity,
    QuizFillUpQuestionEntity,
    QuizMatchingDragDropQuestionEntity,
    QuizMatchingDropDownQuestionEntity,
    QuizMultipleChoiceQuestionEntity,
    QuizMultipleResponseQuestionEntity,
    QuizQuizzesEntity,
    QuizReReportEntity,
    RecipeEntity,
    ReimbursementCreateFormsEntity,
    ReimbursementReportsEntity,
    ReimbursementSubmitedFormsEntity,
    RequestEventReportsEntity,
    ScheduleChallengeEntity,
    ScheduleChallengeJoinUsersEntity,
    SliderSettingsEntity,
    SpouseSettingsEntity,
    SquareUsersEntity,
    SquaresEntity,
    StepCheckpointsEntity,
    SubmitedFormsEntity,
    SurveyQuestionsEntity,
    SurveyReportEntity,
    SurveyUserAnswersEntity,
    TeamMembersEntity,
    TeamsEntity,
    TobaccoUsesEntity,
    TokensEntity,
    UserDetailsEntity,
    UserEntity,
    UserLoginEntity,
    UserSettingsEntity,
    WeeksStepsEntity,
    WeeksUsersEntity,
    WeightRequestEntity,
    WellnessAssignmentEntity,
    ZipDownloadsEntity,
    activityReportEntity,
    appConstant,
    emotionalwellbeingReportsEntity,
    CompanyDashboardClickEntity,
    CompanyDashboardEntity,
    BillboardReportEntity, AssessmentHaOptionsEntity, AssessmentCohortReportsEntity,
    HealthReReportEntity,
    BiometricHealthRequestEntity, BiometricReportsEntity
} from '@common-constants';
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { ClientProxyFactory, Transport } from '@nestjs/microservices';
import { ScheduleModule } from '@nestjs/schedule';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CronCommonService } from './common/commonFunctions';
import { AppCronConfigProvider } from './config/app-cron-config-provider.service';
import { AppCronConfigModule } from './config/app-cron-config.module';
import {
    ActivityFeedService,
    ActivityLogService,
    ActivityReportService,
    AssessmentEmotionalAssessmentAnswerService,
    AssessmentEmotionalAssessmentService,
    AssessmentHraBiometricService,
    AssessmentOptionsService, AssessmentQuestionsService,
    AssessmentResultsService,
    AssessmentService, AssessmentTabsService,
    BioWeightService,
    BiometricOrgSettingService, BiometricService,
    CampaignAnnualReportController,
    CampaignService,
    ChallengeExternalLinkService,
    ChallengeService,
    CommitmentLevelsService,
    CommunicationTemplateTextsService,
    CompanyService,
    CovidReportService,
    CreateFormsService,
    CronService,
    CustomPointService,
    CustomPointUploadService,
    DentistsService,
    DepartmentCronService,
    DepartmentService,
    DownloadFormsService, EhaDetailReportService,
    EngagementComparisonService,
    FitnessActivityService,
    FitnessVideoClickService,
    FitnessVideosService,
    FoodFeedService,
    FormInstructionsService,
    FtBiometricsService,
    HealthActivityService,
    HealthRequestService,
    HealthUsersActivityService,
    HraQuestionsService,
    ImportUserRequestService,
    IncentiveReportsService,
    LocationCronService,
    LocationService,
    MediaFitnessVideoReportService,
    MilesCustomPointUploadService,
    MoveMoreParksService,
    MyPlanActivityService,
    MyPlanAssignPlanService,
    MyPlanAssignRuleService,
    MyPlanAssignUserPlanService,
    MyPlanBlocksService,
    MyPlanCompleteActivityService,
    MyPlanCompleteBlockService,
    MyPlanJoinUserPlanService,
    MyPlanPlansService,
    MyPlanReportController,
    IncentiveReportController,
    OrgCensusReportController,
    OrgCensusReportsService,
    CampaignReportController,
    CohortReportController,
    OptometristsService,
    OrgBiometricService,
    QuestionsService,
    QuickLinkClicksService,
    QuickLinkReportService,
    QuickLinkService,
    QuizQuizzesService,
    ScheduleChallengeJoinUsersService,
    ScheduleChallengeService,
    SettingsService,
    SkipCronService,
    StepCheckpointsService,
    SubmitFormsService,
    SystemCronService,
    TeamMembersService,
    TerminateCronService,
    UploadCronService,
    UserDetailsService,
    UserService,
    UserSettingsService,
    WeeksUsersService,
    WeightCustomPointUploadService,
    WeightRequestService,
    WellBeingCategoryService,
    ReportMenuSettingsService, HealthReportService, HraOptionsService, BiometricReportsService, PhysicianTempsService
} from './module';
import { ActivityService } from './module/acitivity/activity.service';
import { CategoryService } from './module/acitivity/category.service';
import { AutoReportSettingService } from './module/autosetting/autoReportSettings.service';
import { CampaignActivityService } from './module/campaign/campaign-activity.service';
import { CampaignRewardService } from './module/campaign/campaign-reward.service';
import { CampaignCategoryService } from './module/campaign/campaigncategory.service';
import { CampaignDashboardService } from './module/campaign/campaigndashboard.service';
import { CustomPointRequestService } from './module/campaign/custom-point-request.service';
import { FrontService } from './module/campaign/front/front.service';
import { FrontCalculationService } from './module/campaign/front/frontcalculation.service';
import { FrontHealthcheckupService } from './module/campaign/front/fronthealthcheckup.service';
import { FrontPointService } from './module/campaign/front/frontpoint.service';
import { FrontPointsForService } from './module/campaign/front/frontpointfor.service';
import { FrontTrackerEventMediaService } from './module/campaign/front/fronttrackermediaevent.service';
import { SliderSettingsService } from './module/campaign/slidersettings.service';
import { SpouseSettingsService } from './module/campaign/spousesettings.service';
import { CensusCustomFieldsService } from './module/census/censuscustomfields.service';
import { CensusCustomFieldsValuesService } from './module/census/censuscustomfieldsvalues.service';
import { CardsService } from './module/challenge/cards/cards.service';
import { ExternalChallengeReportService, FitnessChallengeReportService, FootballChallengeReportService, FootballStepChallengeReportService, MoveChallengeReportService, StepsChallengeReportService, TrekStepsChallengeReportService } from './module/challenge/challengeReport';
import { BingoChallengeReportService } from "./module/challenge/challengeReport/bingochallengereport.service";
import { ChallengeReportService } from './module/challenge/challengeReport/challengeReport.service';
import { HealthyhabitactivityChallengeReportService } from "./module/challenge/challengeReport/healthyhabitactivitychallengereport.service";
import { HealthyhabitChallengeReportService } from "./module/challenge/challengeReport/healthyhabitchallengereport.service";
import { HealthyhabitreqbasedChallengeReportService } from "./module/challenge/challengeReport/healthyhabitreqbasedchallengereport.service";
import { HydrateChallengeReportService } from './module/challenge/challengeReport/hydratechallengereport.service';
import { OlympicsChallengeReportService } from "./module/challenge/challengeReport/olympics-challenge-report.service";
import { RandomactkindnessChallengeReportService } from "./module/challenge/challengeReport/randomactkindnesschallengereport.service";
import { RecipeChallengeReportService } from './module/challenge/challengeReport/recipechallengereport.service';
import { SleepChallengeReportService } from './module/challenge/challengeReport/sleepchallengereport.service';
import { WeightChallengeReportService } from './module/challenge/challengeReport/weightchallengereport.service';
import { RecipeService } from './module/challenge/recipe/recipe.service';
import { SquaresService } from './module/challenge/squares/squares.service';
import { SquareUsersService } from './module/challenge/squareusers/squareusers.service';
import { TeamsService } from './module/challenge/team/teams.service';
import { TokensService } from './module/challenge/tokens/tokens.service';
import { UserChallengeHelperService } from './module/challenge/userChallengeHelper.service';
import { IncentiveReportHelperService } from './module/incentivereports/incentiveReportHelper.service';
import { WeekStepsService } from './module/challenge/week/weeksteps.service';
import { SortingService, UrlManageService } from './module/common';
import { ActivePluginService, WellnessAssignmentService } from './module/company';
import { InterlinksService } from './module/company/interlinks.service';
import { LocationServices } from './module/company/location.service';
import { MassCommunicationService } from './module/company/masscomunication.service';
import { CompanyNumberOfLiveReportsService } from './module/company/numberOfLiveReport.service';
import { DocumentService } from './module/datamanagement/document/document.service';
import { WellBeingPostClickService, WellBeingPostService, WellbeingReportService } from './module/emotional-well-being';
import {
    EventCategoryService,
    EventExternalLinkService,
    EventGlobalEventsService,
    EventReportHelper,
    EventUserBookingListsService,
    RequestEventReportsService,
} from './module/events';
import { EventService } from './module/events/events.service';
import { AgeActivityService } from './module/healthcheckup/ageactivity/ageactivity.service';
import { AuthorizationsService } from './module/healthcheckup/authorizations/authorizations.service';
import { BiometricsService } from './module/healthcheckup/biometrics/biometrics.service';
import { EngagementService } from './module/healthcheckup/engagement/engagement.service';
import { HippaReportService } from './module/healthcheckup/hippareport/hippareport.service';
import { TobaccoUsesService } from './module/healthcheckup/tobacco-uses/tobacco-uses.service';
import { QuizReportService } from './module/quiz/quiz-report/quizreport.service';
import { QuizReportHelperService } from './module/quiz/quizreporthelper.service';
import { ReimbursementService } from './module/reimbursement/reimbusement.service';
import { ReimbursementReportService } from './module/reimbursement/reimbusementreport.service';
import { EngagementComparisonReportService } from "./module/reports";
import { BiometricResultReportService } from "./module/reports/biometric-result-report/biometric-result-report.service";
import { CampaignDataHelperService } from './module/reports/campaign-annual-report/campaigndatahelper.service';
import { HraDetailReportService } from "./module/reports/hra-detail-report/hra-detail-report.service";
import { MyPlanReportService } from './module/reports/my-plan-report/my-plan-report.service';
import { SurveyQuestionsService } from './module/survey/surveyquestion.service';
import { SurveyReportService } from './module/survey/surveyreport.service';
import { SurveyUserAnswersService } from './module/survey/surveyuseranswers.service';
import { BodyFeedService } from './module/tracker/body-feeds/body-feeds.service';
import { UserLoginService } from './module/user';
import { BillboardReportService } from './module/company/billboard-report/billboard-report.service';
import { DashboardService } from './module/company/billboard-report/dashboard.service';
import { DashboardClickService } from './module/company/billboard-report/dashboard-click.service';
import { AggregateReportService } from './module/healthcheckup/aggregatereport/aggregatereport.service';
import { RelayRaceChallengeReportService } from './module/challenge/challengeReport/relayracechallengereport.service';
import { CohortReportsService } from './module/cohortreports/cohortreports.service';
import { HealthReReportService } from './module/healthcheckup/healthrereport.service';
import {BiometricHealthRequestAddService, BiometricHealthRequestService} from "./module/healthcheckup/biometric-health-request";

@Module({
    imports: [
        ScheduleModule.forRoot(),
        ConfigModule.forRoot({ isGlobal: true }),
        TypeOrmModule.forRootAsync({
            imports: [AppCronConfigModule],
            name: appConstant.MAIN.toLowerCase(),
            useFactory: (configService: AppCronConfigProvider) => {
                return {
                    ...configService.typeOrmConfig,
                    name: configService.typeOrmConfig.name,
                };
            },
            inject: [AppCronConfigProvider],
        }),
        TypeOrmModule.forRootAsync({
            imports: [AppCronConfigModule],
            name: appConstant.READ_REPLICA.toLowerCase(),
            useFactory: (configService: AppCronConfigProvider) => {
                return {
                    ...configService.typeOrmConfig1,
                    name: configService.typeOrmConfig1.name,
                };
            },
            inject: [AppCronConfigProvider],
        }),
        TypeOrmModule.forFeature(
            [
                ImportUserRequestEntity,
                DepartmentsEntity,
                CompaniesEntity,
                CompanySettingsEntity,
                CompanyReportMenuSettingsEntity,
                LocationsEntity,
                DownloadFormsEntity,
                FormInstructionsEntity,
                UserEntity,
                TokensEntity,
                AuthorizationsEntity,
                AgeActivityEntity,
                DiseaseFormsEntity,
                DiseasesEntity,
                DiseaseFormCoverPagesEntity,
                DentistsEntity,
                UserSettingsEntity,
                PhysicianTempsEntity,
                CommunicationTemplateTextsEntity,
                ZipDownloadsEntity,
                CovidQuestionsEntity,
                WellnessAssignmentEntity,
                CensusCustomFieldsValuesEntity,
                CovidReportEntity,
                CensusCustomFieldsEntity,
                QuickLinkClicksEntity,
                QuickLinkEntity,
                QuickLinkReReportEntity,
                QuickLinkReportEntity,
                MediaFitnessVideoClickEntity,
                MediaFitnessVideosReportEntity,
                FitnessActivityEntity,
                AutoReportSettingsEntity,
                EmotionalWellBeingPostClickEntity,
                emotionalwellbeingReportsEntity,
                CompanyDashboardClickEntity,
                CompanyDashboardEntity,
                BillboardReportEntity,
                SurveyReportEntity,
                SurveyQuestionsEntity,
                activityReportEntity,
                ActivityFeedsEntity,
                FoodFeedsEntity,
                CustomPointEntity,
                CampaignActivityEntity,
                CampaignEntity,
                CampaignRewardEntity,
                CustomPointRequestEntity,
                ReimbursementCreateFormsEntity,
                ReimbursementReportsEntity,
                ReimbursementSubmitedFormsEntity,
                FormSendRequestUserEntity,
                IncentiveReportsEntity,
                MyPlanPlansEntity,
                AssessmentHaQuestionsEntity,
                AssessmentHaOptionsEntity,
                ScheduleChallengeEntity,
                ChallengeEntity,
                MediaFitnessVideosEntity,
                AssessmentsEntity,
                CompanyMasscommunicationEntity,
                EventEntity,
                HealthUsersActivityEntity,
                HealthRequestEntity,
                HealthActivityEntity,
                MyPlanBlocksEntity,
                MyPlanActivityEntity,
                MyPlanAssignPlanEntity,
                MyPlanCompleteActivityEntity,
                MyPlanCompleteBlockEntity,
                MyPlanAssignUserPlanEntity,
                TeamsEntity,
                MyPlanJoinUserPlanEntity,
                MyPlanAssignRuleEntity,
                UserDetailsEntity,
                BiometricsEntity,
                EventUserBookingListsEntity,
                TobaccoUsesEntity,
                ScheduleChallengeJoinUsersEntity,
                AssessmentHraBiometricEntity,
                FtBiometricsEntity,
                AssessmentResultsEntity,
                AssessmentEmotionalAssessmentEntity,
                AssessmentEmotionalAssessmentAnswerEntity,
                AssessmentOptionsEntity,
                QuizQuizzesEntity,
                ActivePluginsEntity,
                DentistsEntity,
                OptometristsEntity,
                SubmitedFormsEntity,
                UserLoginEntity,
                EventCategoryEntity,
                EmotionalWellBeingPostEntity,
                BodyFeedsEntity,
                EmotionalWellBeingCategoryEntity,
                RecipeEntity,
                EventGlobalEventsEntity,
                EventExternalLinkEntity,
                RequestEventReportsEntity,
                BioWeightEntity,
                SurveyUserAnswersEntity,
                CompanyNumberOfLiveReportsEntity,
                ActivityEntity,
                CampaignCategoryEntity,
                QuizReReportEntity,
                BiometricEntity,
                BiometricOrgSettingEntity,
                OrgBiometricEntity,
                AssessmentTabsEntity,
                AssessmentQuestionsEntity,
                InterlinksEntity,
                AgeActivityEntity,
                CategoryEntity,
                DataManagementDocumentEntity,
                CampaignChallengeEntity,
                InsuranceRewardEntity,
                CashRewardEntity,
                OtherRewardEntity,
                SliderSettingsEntity,
                SpouseSettingsEntity,
                WeightRequestEntity,
                SquaresEntity,
                SquareUsersEntity,
                CardsEntity,
                TeamMembersEntity,
                WeeksStepsEntity,
                WeeksUsersEntity,
                StepCheckpointsEntity,
                QuizDetailsEntity,
                QuizMultipleChoiceQuestionEntity,
                QuizFillUpQuestionEntity,
                QuizMatchingDragDropQuestionEntity,
                QuizMultipleResponseQuestionEntity,
                QuizMatchingDropDownQuestionEntity,
                ChallengeExternalLinkEntity,
                EngagementComparisonReportsEntity,
                CommitmentLevelsEntity,
                MoveMoreParksEntity,
                AssessmentCohortReportsEntity,
                HealthReReportEntity,
                BiometricHealthRequestEntity,
                BiometricReportsEntity,
            ],
            appConstant.READ_REPLICA.toLowerCase(),
        ),
        TypeOrmModule.forFeature(
            [
                ImportUserRequestEntity,
                DepartmentsEntity,
                CompaniesEntity,
                CompanySettingsEntity,
                CompanyReportMenuSettingsEntity,
                LocationsEntity,
                DownloadFormsEntity,
                FormInstructionsEntity,
                UserEntity,
                TokensEntity,
                AuthorizationsEntity,
                AgeActivityEntity,
                DiseaseFormsEntity,
                DiseasesEntity,
                DiseaseFormCoverPagesEntity,
                DentistsEntity,
                UserSettingsEntity,
                PhysicianTempsEntity,
                CommunicationTemplateTextsEntity,
                ZipDownloadsEntity,
                CovidQuestionsEntity,
                WellnessAssignmentEntity,
                CensusCustomFieldsValuesEntity,
                CovidReportEntity,
                CensusCustomFieldsEntity,
                QuickLinkClicksEntity,
                QuickLinkEntity,
                QuickLinkReReportEntity,
                QuickLinkReportEntity,
                MediaFitnessVideoClickEntity,
                MediaFitnessVideosReportEntity,
                FitnessActivityEntity,
                AutoReportSettingsEntity,
                EmotionalWellBeingPostClickEntity,
                emotionalwellbeingReportsEntity,
                CompanyDashboardClickEntity,
                CompanyDashboardEntity,
                BillboardReportEntity,
                SurveyReportEntity,
                SurveyQuestionsEntity,
                activityReportEntity,
                ActivityFeedsEntity,
                FoodFeedsEntity,
                CustomPointEntity,
                CampaignActivityEntity,
                CampaignEntity,
                CampaignRewardEntity,
                CustomPointRequestEntity,
                ReimbursementCreateFormsEntity,
                ReimbursementReportsEntity,
                ReimbursementSubmitedFormsEntity,
                FormSendRequestUserEntity,
                IncentiveReportsEntity,
                MyPlanPlansEntity,
                AssessmentHaQuestionsEntity,
                AssessmentHaOptionsEntity,
                ScheduleChallengeEntity,
                ChallengeEntity,
                MediaFitnessVideosEntity,
                AssessmentsEntity,
                CompanyMasscommunicationEntity,
                EventEntity,
                HealthUsersActivityEntity,
                HealthRequestEntity,
                HealthActivityEntity,
                MyPlanBlocksEntity,
                MyPlanActivityEntity,
                MyPlanAssignPlanEntity,
                MyPlanCompleteActivityEntity,
                MyPlanCompleteBlockEntity,
                MyPlanAssignUserPlanEntity,
                TeamsEntity,
                MyPlanJoinUserPlanEntity,
                MyPlanAssignRuleEntity,
                UserDetailsEntity,
                BiometricsEntity,
                EventUserBookingListsEntity,
                TobaccoUsesEntity,
                ScheduleChallengeJoinUsersEntity,
                AssessmentHraBiometricEntity,
                FtBiometricsEntity,
                AssessmentResultsEntity,
                AssessmentEmotionalAssessmentEntity,
                AssessmentEmotionalAssessmentAnswerEntity,
                AssessmentOptionsEntity,
                QuizQuizzesEntity,
                ActivePluginsEntity,
                DentistsEntity,
                OptometristsEntity,
                SubmitedFormsEntity,
                UserLoginEntity,
                EventCategoryEntity,
                EmotionalWellBeingPostEntity,
                BodyFeedsEntity,
                EmotionalWellBeingCategoryEntity,
                RecipeEntity,
                EventGlobalEventsEntity,
                EventExternalLinkEntity,
                RequestEventReportsEntity,
                BioWeightEntity,
                CompanyNumberOfLiveReportsEntity,
                ActivityEntity,
                CampaignCategoryEntity,
                QuizReReportEntity,
                BiometricEntity,
                BiometricOrgSettingEntity,
                OrgBiometricEntity,
                AssessmentTabsEntity,
                AssessmentQuestionsEntity,
                InterlinksEntity,
                AgeActivityEntity,
                CategoryEntity,
                DataManagementDocumentEntity,
                CampaignChallengeEntity,
                InsuranceRewardEntity,
                CashRewardEntity,
                OtherRewardEntity,
                SliderSettingsEntity,
                SpouseSettingsEntity,
                WeightRequestEntity,
                SquaresEntity,
                SquareUsersEntity,
                CardsEntity,
                TeamMembersEntity,
                WeeksStepsEntity,
                WeeksUsersEntity,
                StepCheckpointsEntity,
                QuizDetailsEntity,
                QuizMultipleChoiceQuestionEntity,
                QuizFillUpQuestionEntity,
                QuizMatchingDragDropQuestionEntity,
                QuizMultipleResponseQuestionEntity,
                QuizMatchingDropDownQuestionEntity,
                ChallengeExternalLinkEntity,
                EngagementComparisonReportsEntity,
                CommitmentLevelsEntity,
                MoveMoreParksEntity,
                AssessmentCohortReportsEntity,
                HealthReReportEntity,
                BiometricHealthRequestEntity,
                BiometricReportsEntity,
            ],
            appConstant.MAIN.toLowerCase(),
        ),
    ],
    controllers: [AppController, MyPlanReportController, IncentiveReportController, CohortReportController, CampaignReportController, OrgCensusReportController],
    providers: [
        AppService,
        CronService,
        MyPlanReportController,
        IncentiveReportController,
        OrgCensusReportController,
        CampaignReportController,
        CohortReportController,
        CampaignAnnualReportController,
        DepartmentCronService,
        SkipCronService,
        SystemCronService,
        UploadCronService,
        TerminateCronService,
        UserService,
        UserSettingsService,
        DepartmentService,
        LocationCronService,
        LocationService,
        CompanyService,
        CommonService,
        CommonArrayService,
        CommonDateService,
        CommonFileService,
        CommonHealthService,
        ImportUserRequestService,
        DownloadFormsService,
        CensusCustomFieldsValuesService,
        CensusCustomFieldsService,
        AutoReportSettingService,
        ReportMenuSettingsService,
        WellBeingPostClickService,
        WellbeingReportService,
        SurveyQuestionsService,
        CovidReportService,
        SettingsService,
        QuestionsService,
        QuickLinkService,
        QuickLinkClicksService,
        QuickLinkReportService,
        FitnessVideoClickService,
        MediaFitnessVideoReportService,
        ActivityFeedService,
        ActivityReportService,
        FoodFeedService,
        FitnessChallengeReportService,
        FitnessActivityService,
        SurveyReportService,
        LocationServices,
        CustomPointService,
        CustomPointUploadService,
        MilesCustomPointUploadService,
        ReimbursementService,
        ReimbursementReportService,
        FormInstructionsService,
        IncentiveReportsService,
        OrgCensusReportsService,
        CampaignService,
        CampaignActivityService,
        CampaignRewardService,
        CustomPointRequestService,
        MyPlanPlansService,
        ScheduleChallengeService,
        ChallengeService,
        FitnessVideosService,
        CreateFormsService,
        AssessmentService,
        CacheService,
        CommunicationTemplateTextsService,
        MassCommunicationService,
        EventService,
        HealthActivityService,
        HealthUsersActivityService,
        HealthRequestService,
        CronCommonService,
        ActivityLogService,
        MyPlanReportService,
        MyPlanBlocksService,
        MyPlanActivityService,
        ChallengeReportService,
        MyPlanAssignPlanService,
        MyPlanCompleteBlockService,
        MyPlanCompleteActivityService,
        MyPlanAssignUserPlanService,
        SleepChallengeReportService,
        TeamsService,
        UserChallengeHelperService,
        IncentiveReportHelperService,
        MyPlanJoinUserPlanService,
        MyPlanAssignRuleService,
        UserDetailsService,
        BiometricsService,
        EventUserBookingListsService,
        AuthorizationsService,
        TobaccoUsesService,
        ScheduleChallengeJoinUsersService,
        AssessmentHraBiometricService,
        FtBiometricsService,
        AssessmentResultsService,
        AssessmentEmotionalAssessmentService,
        AssessmentEmotionalAssessmentAnswerService,
        AssessmentOptionsService,
        HydrateChallengeReportService,
        QuizQuizzesService,
        ActivePluginService,
        DentistsService,
        OptometristsService,
        SubmitFormsService,
        UserLoginService,
        EventCategoryService,
        WellBeingPostService,
        BodyFeedService,
        WellBeingCategoryService,
        RecipeService,
        RecipeChallengeReportService,
        EventReportHelper,
        EventGlobalEventsService,
        EventExternalLinkService,
        RequestEventReportsService,
        BioWeightService,
        WeightChallengeReportService,
        SurveyUserAnswersService,
        CompanyNumberOfLiveReportsService,
        ActivityService,
        CampaignCategoryService,
        QuizReportService,
        BiometricService,
        BiometricOrgSettingService,
        OrgBiometricService,
        BiometricResultReportService,
        HippaReportService,
        EhaDetailReportService,
        HraDetailReportService,
        HraQuestionsService,
        HraOptionsService,
        AssessmentTabsService,
        AssessmentQuestionsService,
        FrontService,
        FrontCalculationService,
        FrontHealthcheckupService,
        FrontPointService,
        FrontPointsForService,
        FrontTrackerEventMediaService,
        SortingService,
        UrlManageService,
        AgeActivityService,
        InterlinksService,
        CategoryService,
        DocumentService,
        CampaignDashboardService,
        SliderSettingsService,
        SpouseSettingsService,
        CampaignDataHelperService,
        WeightRequestService,
        WeightCustomPointUploadService,
        FootballChallengeReportService,
        BingoChallengeReportService,
        HealthyhabitChallengeReportService,
        HealthyhabitreqbasedChallengeReportService,
        HealthyhabitactivityChallengeReportService,
        RandomactkindnessChallengeReportService,
        SquaresService,
        CardsService,
        TokensService,
        SquareUsersService,
        EngagementService,
        StepsChallengeReportService,
        TeamMembersService,
        WeekStepsService,
        WeeksUsersService,
        OlympicsChallengeReportService,
        FootballStepChallengeReportService,
        StepCheckpointsService,
        QuizReportHelperService,
        EngagementComparisonReportService,
        ChallengeExternalLinkService,
        ExternalChallengeReportService,
        TrekStepsChallengeReportService,
        MoveChallengeReportService,
        MoveMoreParksService,
        CommitmentLevelsService,
        WellnessAssignmentService,
        EngagementComparisonService,
        BillboardReportService,
        DashboardService,
        DashboardClickService,
        HealthReportService,
        AggregateReportService,
        RelayRaceChallengeReportService,
        CohortReportsService,
        HealthReReportService,
        BiometricHealthRequestService,
        BiometricHealthRequestAddService,
        BiometricReportsService,
        PhysicianTempsService,
        {
            provide: 'POSTCODES_SERVICE',
            inject: [ConfigService],
            useFactory: () => {
                return ClientProxyFactory.create({
                    transport: Transport.TCP,
                    options: {
                        host: process.env.TIMEZONES_SERVICE_HOST_PROD,
                        port: Number(process.env.TIMEZONES_SERVICE_PORT_PROD),
                    },
                });
            },
        },
        {
            provide: 'COMMON_SERVICE',
            inject: [ConfigService],
            useFactory: () => {
                return ClientProxyFactory.create({
                    transport: Transport.TCP,
                    options: {
                        host: process.env.COMMON_SERVICE_HOST_PROD,
                        port: Number(process.env.COMMON_SERVICE_PORT_PROD),
                    },
                });
            },
        },
        {
            provide: 'TIMEZONE_SERVICE',
            inject: [ConfigService],
            useFactory: () => {
                return ClientProxyFactory.create({
                    transport: Transport.TCP,
                    options: {
                        host: process.env.TIMEZONES_SERVICE_HOST_PROD,
                        port: Number(process.env.TIMEZONES_SERVICE_PORT_PROD),
                    },
                });
            },
        },
        {
            provide: 'ACTIVITYLOG_SERVICE',
            inject: [ConfigService],
            useFactory: () => {
                return ClientProxyFactory.create({
                    transport: Transport.TCP,
                    options: {
                        host: process.env.ACTIVITYLOG_SERVICE_HOST_PROD,
                        port: Number(process.env.ACTIVITYLOG_SERVICE_PORT_PROD),
                    },
                });
            },
        },
    ],
})
export class AppModule {}
