import { Allow } from 'class-validator';
export class UpdateIncentiveReportsInput {
    @Allow() id: number;
    @Allow() org_id: number;
    @Allow() user_id: number;
    @Allow() user_role: number;
    @Allow() membership_code: string;
    @Allow() condition: string;
    @Allow() report_type: string;
    @Allow() file_name: string;
    @Allow() total_download: number;
    @Allow() request_date: string;
    @Allow() email: string;
    @Allow() is_range: number;
    @Allow() start_date_range: string;
    @Allow() end_date_range: string;
    @Allow() camp_id: string;
    @Allow() engagement_report: number;
    @Allow() request_source: number;
    @Allow() email_status: number;
    @Allow() report_setting_id: number;
    @Allow() auto_report_type: number;
    @Allow() auto_report_zip_password: string;
    @Allow() report_item_status: string;
    @Allow() report_item_type: string;
    @Allow() send_cc_emails: string;
    @Allow() request_timezone: string;
    @Allow() request_timezone_time: string;
    @Allow() error_message: string;
    @Allow() status: number;
}
