import { Allow } from 'class-validator';
export class CreateCampaignCategoryInput {
    @Allow() id: number;
    @Allow() campaign_id: number;
    @Allow() order_id: number;
    @Allow() category_id: number;
    @Allow() reward_id: number;
    @Allow() cust_name: string;
    @Allow() cust_description: string;
    @Allow() quentity: string;
    @Allow() required_by_user: string;
    @Allow() required_by_spouse: string;
    @Allow() frequincy: string;
    @Allow() frequincy_max_point: string;
    @Allow() point_for_each: string;
    @Allow() max_point: string;
    @Allow() ac_max: string;
    @Allow() ac_min: string;
    @Allow() per_change: string;
    @Allow() alt_activity: number;
    @Allow() alt_act_point: string;
    @Allow() reward_for: number;
    @Allow() is_hidden_on_activity_page: number;
    @Allow() start_date: string;
    @Allow() end_date: string;
    @Allow() status: number;
    @Allow() point_end_date: string;
    @Allow() after_deadline_date: string;
    @Allow() consider_after_deadline: number;
}
