import { Allow } from 'class-validator';
export class CreateCompanyContractInput {
    @Allow() id: number;
    @Allow() org_id: number;
    @Allow() billing_email: string;
    @Allow() billing_frequency: number;
    @Allow() billing_name: string;
    @Allow() engagement_manager_name: string;
    @Allow() package: number;
    @Allow() expense_description_amount: string;
    @Allow() reminder_contract: string;
    @Allow() contract_reminder_email: string;
    @Allow() status: number;
    @Allow() created_by: number;
    @Allow() updated_by: number;
    @Allow() contract_start_date: string;
    @Allow() contract_end_date: string;
    @Allow() billing_start_date: string;
    @Allow() billing_end_date: string;
    @Allow() date_of_expense_submission: string;
    @Allow() broker: string;
    @Allow() csa: string;
    @Allow() baa: string;
    @Allow() billing_email_cc: string;
    @Allow() notes_for_data_team: string;
    @Allow() notes_for_design_team: string;
    @Allow() branding_guideline_text: string;
    @Allow() branding_guideline_image: string;
    @Allow() industry: string;
    @Allow() additional_agreement: string;
}
