import { Allow } from 'class-validator';
export class CreateCompanyDashboardInput {
    @Allow() id: number;
    @Allow() org_id: number;
    @Allow() square_img: string;
    @Allow() square_img_link: string;
    @Allow() square_img_link_isin: string;
    @Allow() square_img_link_id: string;
    @Allow() mob_square_img: string;
    @Allow() status: number;
    @Allow() added_by: number;
    @Allow() reference_id: number;
    @Allow() displaybasedon: number;
    @Allow() from_date: string;
    @Allow() to_date: string;
    @Allow() image_order: number;
    @Allow() imglug_id: number;
    @Allow() imgopt_id: number;
    @Allow() square_img_activity: number;
    @Allow() dimg_eligibility: number;
    @Allow() dimg_visibility: number;
    @Allow() dimg_visibility_ids: string;
    @Allow() dimg_healthplan: number;
    @Allow() dimg_healthplanname: string;
    @Allow() dashboard_data: any;
    @Allow() slider_limit: number;
    @Allow() eligibility: number;
    @Allow() square_img_back_color: string;
    @Allow() square_img_icon_color: string;
    @Allow() square_img_text: string;
    @Allow() square_img_text_color: string;
}
